[package]
name = "zero-net"
description = "网络栈 — 基于 hyper/reqwest 的 HTTP/HTTPS 请求封装"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zero-product-version = { workspace = true }
zero-runtime-config = { workspace = true }
zero-psl = { workspace = true }
hyper = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "gzip", "brotli", "deflate"] }
tokio = { workspace = true }
url = { workspace = true }
encoding_rs = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
tungstenite = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "net_bench"
harness = false
