[package]
name = "zero-android-browser"
description = "ZeroWeb Android browser host native library"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "zero_android_browser"
crate-type = ["cdylib"]

[features]
android-renderer = ["dep:zero-renderer"]

[dependencies]
jni = "0.21.1"
zero-image-decoder = { path = "../../image-decoder" }
zero-compositor = { path = "../../compositor" }
zero-browser-shell = { path = "../../../crates/browser-shell" }
zero-protocol = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
libc = "0.2"
zero-renderer = { path = "../../renderer", optional = true }
