use super::InlineReftestDef;
use crate::reftest::ReftestCategory;

const REFTESTS: &[InlineReftestDef] = &[
    // ── 1-5: 颜色 ──
    InlineReftestDef {
        id: "css21/color-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100px;height:100px;background:red;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100px;height:100px;background:#FF0000;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/color-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100px;height:100px;background:blue;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100px;height:100px;background:rgb(0,0,255);\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/color-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100px;height:100px;background:green;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100px;height:100px;background:#008000;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/color-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100px;height:100px;background:yellow;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100px;height:100px;background:rgb(255,255,0);\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/color-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:50px;height:50px;background:red;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:50px;height:50px;background:blue;\"></div></body></html>",
        is_match: false,
    },
    // ── 6-10: 背景 ──
    InlineReftestDef {
        id: "css21/background-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;background:#008000;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/background-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:orange;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:#FFA500;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/background-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:purple;\"></div><div style=\"width:100px;height:50px;background:gold;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:#800080;\"></div><div style=\"width:100px;height:50px;background:#FFD700;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/background-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;background:cyan;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;background:magenta;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/background-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100%;height:100%;background:teal;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100%;height:100%;background:#008080;\"></div></body></html>",
        is_match: true,
    },
    // ── 11-15: 边框 ──
    InlineReftestDef {
        id: "css21/border-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border:10px solid black;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border:10px solid #000000;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/border-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border-top:5px solid red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border-top:5px solid #FF0000;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/border-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:60px;height:60px;border:20px solid blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:60px;height:60px;border:20px solid green;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/border-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border-left:10px solid orange;border-right:10px solid orange;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border-left:10px solid #FFA500;border-right:10px solid #FFA500;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/border-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border:none;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border:0;background:green;\"></div></body></html>",
        is_match: true,
    },
    // ── 16-20: 盒模型 ──
    InlineReftestDef {
        id: "css21/box-model-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;margin:20px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;margin:20px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/box-model-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;background:blue;padding:10px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;background:blue;padding:10px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/box-model-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;background:red;padding:10px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;background:red;padding:20px;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/box-model-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:green;margin:0;\"></div><div style=\"width:100px;height:50px;background:blue;margin:0;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:green;margin:0;\"></div><div style=\"width:100px;height:50px;background:blue;margin:0;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/box-model-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:40px;background:red;margin:10px;\"></div><div style=\"width:80px;height:40px;background:blue;margin:10px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:40px;background:red;margin:10px;\"></div><div style=\"width:80px;height:40px;background:blue;margin:10px;\"></div></body></html>",
        is_match: true,
    },
    // ── 21-25: 定位 ──
    InlineReftestDef {
        id: "css21/position-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:green;\"><div style=\"position:absolute;top:10px;left:10px;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:green;\"><div style=\"position:absolute;top:10px;left:10px;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/position-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:blue;\"><div style=\"position:relative;top:20px;left:20px;width:40px;height:40px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:blue;\"><div style=\"position:relative;top:20px;left:20px;width:40px;height:40px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/position-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:green;\"><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:green;\"><div style=\"position:absolute;top:30px;left:30px;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/position-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:#eee;\"><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:#eee;\"><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/position-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;bottom:10px;right:10px;width:30px;height:30px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;bottom:10px;right:10px;width:30px;height:30px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 26-30: 显示 ──
    InlineReftestDef {
        id: "css21/display-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:none;width:100px;height:100px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/display-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:block;width:100px;height:100px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/display-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;display:none;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/display-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:green;visibility:hidden;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/display-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:green;\"></div><div style=\"width:100px;height:100px;background:red;visibility:hidden;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:green;\"></div><div style=\"width:100px;height:100px;background:red;visibility:hidden;\"></div></body></html>",
        is_match: true,
    },
    // ── 31-35: 尺寸 ──
    InlineReftestDef {
        id: "css21/size-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/size-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:200px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:200px;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/size-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:150px;height:150px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:150px;height:100px;background:green;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/size-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50%;height:50%;background:orange;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50%;height:50%;background:orange;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/size-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;background:red;\"></div></body></html>",
        is_match: false,
    },
    // ── 36-40: Flexbox ──
    InlineReftestDef {
        id: "css21/flex-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"flex:1;background:red;\"></div><div style=\"flex:1;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"flex:1;background:red;\"></div><div style=\"flex:1;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/flex-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"width:100px;height:100px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"width:100px;height:100px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/flex-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;width:100px;height:200px;\"><div style=\"flex:1;background:green;\"></div><div style=\"flex:1;background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;width:100px;height:200px;\"><div style=\"flex:1;background:green;\"></div><div style=\"flex:1;background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/flex-004",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"width:100px;height:100px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"width:100px;height:100px;background:blue;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/flex-005",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;justify-content:center;width:200px;height:100px;\"><div style=\"width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;justify-content:center;width:200px;height:100px;\"><div style=\"width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 41-45: Grid ──
    InlineReftestDef {
        id: "css21/grid-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/grid-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:100px;\"><div style=\"background:green;\"></div><div style=\"background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:100px;\"><div style=\"background:green;\"></div><div style=\"background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/grid-003",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;grid-template-rows:50px 50px;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div><div style=\"background:green;\"></div><div style=\"background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;grid-template-rows:50px 50px;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div><div style=\"background:green;\"></div><div style=\"background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 46-50: 嵌套/复杂布局 ──
    InlineReftestDef {
        id: "css21/nested-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;background:red;\"><div style=\"width:100px;height:100px;background:blue;\"><div style=\"width:50px;height:50px;background:green;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;background:red;\"><div style=\"width:100px;height:100px;background:blue;\"><div style=\"width:50px;height:50px;background:green;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/nested-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"><div style=\"width:80px;height:80px;background:blue;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/siblings-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/siblings-002",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:red;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/complex-001",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"width:100px;height:50px;background:red;float:left;\"></div><div style=\"width:100px;height:50px;background:blue;float:left;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"width:100px;height:50px;background:red;float:left;\"></div><div style=\"width:100px;height:50px;background:blue;float:left;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 51-55: 文本基础 ──
    InlineReftestDef {
        id: "css21/text-001",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"color:red;\">Hello</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"color:red;\">Hello</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/text-002",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:blue;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/text-003",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"font-size:16px;\">Size 16</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-size:16px;\">Size 16</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/text-004",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"font-weight:bold;\">Bold</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-weight:bold;\">Bold</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/text-005",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-align:center;\">Center</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-align:center;\">Center</div></body></html>",
        is_match: true,
    },
    // ── 116-120: 边框样式 ──
    InlineReftestDef {
        id: "css21/border-solid-vs-equivalent",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:5px solid red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border-top:5px solid red;border-right:5px solid red;border-bottom:5px solid red;border-left:5px solid red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/border-different-sides",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border-top:10px solid red;border-right:5px solid blue;border-bottom:3px solid green;border-left:8px solid orange;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border-top:10px solid red;border-right:5px solid blue;border-bottom:3px solid green;border-left:8px solid orange;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/border-width-variation",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:2px solid red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:15px solid red;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/border-with-padding",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:5px solid red;padding:10px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:5px solid red;padding:10px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/border-box-sizing-content-box",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;padding:10px;border:5px solid red;box-sizing:content-box;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;padding:10px;border:5px solid red;box-sizing:content-box;background:blue;\"></div></body></html>",
        is_match: true,
    },
    // ── 121-125: Overflow 行为 ──
    InlineReftestDef {
        id: "css21/overflow-hidden-clips",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;overflow:hidden;background:red;\"><div style=\"width:200px;height:200px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;overflow:hidden;background:red;\"><div style=\"width:200px;height:200px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/overflow-visible-no-clip",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;overflow:visible;background:red;\"><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;overflow:visible;background:red;\"><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/overflow-hidden-vs-visible",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:hidden;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:visible;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css21/overflow-hidden-nested",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;overflow:hidden;background:red;\"><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/overflow-with-margin-child",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;overflow:hidden;background:red;\"><div style=\"width:50px;height:50px;margin:10px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;overflow:hidden;background:red;\"><div style=\"width:50px;height:50px;margin:10px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 126-130: Margin 折叠验证 ──
    InlineReftestDef {
        id: "css21/margin-collapse-siblings",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/margin-collapse-parent-child",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"background:red;\"><div style=\"margin-top:20px;width:100px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"background:red;\"><div style=\"margin-top:20px;width:100px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/margin-no-collapse-bfc",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"overflow:hidden;background:red;\"><div style=\"margin-top:20px;width:100px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"overflow:hidden;background:red;\"><div style=\"margin-top:20px;width:100px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/margin-auto-center-fixed-width",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:50px;margin:0 auto;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:50px;margin-left:auto;margin-right:auto;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/margin-zero-body-reset",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0;padding:0\"><div style=\"width:100px;height:100px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0;padding:0\"><div style=\"width:100px;height:100px;background:red;\"></div></body></html>",
        is_match: true,
    },
    // ── 131-135: Position 定位进阶 ──
    InlineReftestDef {
        id: "css21/absolute-in-relative-container",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;background:red;\"><div style=\"position:absolute;top:10px;left:10px;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;background:red;\"><div style=\"position:absolute;top:10px;left:10px;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/absolute-right-bottom",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;background:red;\"><div style=\"position:absolute;right:10px;bottom:10px;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;background:red;\"><div style=\"position:absolute;right:10px;bottom:10px;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/relative-offset-no-layout-change",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"position:relative;top:10px;left:10px;width:100px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"position:relative;top:10px;left:10px;width:100px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/z-index-stacking-order",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:red;z-index:2;\"></div><div style=\"position:relative;width:100px;height:100px;background:blue;margin-top:-50px;z-index:1;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:red;z-index:2;\"></div><div style=\"position:relative;width:100px;height:100px;background:blue;margin-top:-50px;z-index:1;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/absolute-overlaps-static",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    // ── 136-140: Quirks mode 专用 ──
    InlineReftestDef {
        id: "css21/quirks-hashless-color",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100px;height:100px;background:FF0000;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100px;height:100px;background:FF0000;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/quirks-numeric-color",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100px;height:100px;background:16711680;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100px;height:100px;background:16711680;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/quirks-unitless-width",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100;height:100;background:red;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100;height:100;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/quirks-unitless-padding",
        category: ReftestCategory::Layout,
        test_html: "<html><body><div style=\"width:100;height:100;padding:10;background:red;\"></div></body></html>",
        ref_html: "<html><body><div style=\"width:100;height:100;padding:10;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css21/quirks-table-height-as-min-height",
        category: ReftestCategory::Layout,
        test_html: "<html><body><table style=\"height:50;background:red;\"><tr><td style=\"width:100;height:100;background:blue;\"></td></tr></table></body></html>",
        ref_html: "<html><body><table style=\"height:50;background:red;\"><tr><td style=\"width:100;height:100;background:blue;\"></td></tr></table></body></html>",
        is_match: true,
    },
];

pub fn reftests() -> &'static [InlineReftestDef] {
    REFTESTS
}
