use super::InlineReftestDef;
use crate::reftest::ReftestCategory;

const REFTESTS: &[InlineReftestDef] = &[
    // ── 1-12: original entries ──
    InlineReftestDef {
        id: "css-display/none-removes-layout",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"display:none;width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/inline-block-same-line",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:100px;height:50px;background:red;\"></div><div style=\"display:inline-block;width:100px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:100px;height:50px;background:red;\"></div><div style=\"display:inline-block;width:100px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/visibility-hidden-preserves-space",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"visibility:hidden;width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"visibility:hidden;width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/block-nested-inline-block",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:#eee;\"><div style=\"display:inline-block;width:80px;height:80px;background:red;\"></div><div style=\"display:inline-block;width:80px;height:80px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:#eee;\"><div style=\"display:inline-block;width:80px;height:80px;background:red;\"></div><div style=\"display:inline-block;width:80px;height:80px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/display-none-vs-visible",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:none;width:100px;height:100px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-display/flex-item-display-none",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:50px;\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"display:none;width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:50px;\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"display:none;width:100px;height:50px;background:blue;\"></div><div style=\"width:100px;height:50px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/grid-item-display-none",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"display:none;background:blue;\"></div><div style=\"background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"display:none;background:blue;\"></div><div style=\"background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/nested-flex-and-grid",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"display:grid;grid-template-rows:1fr 1fr;width:100px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div></div><div style=\"width:100px;height:100px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"display:grid;grid-template-rows:1fr 1fr;width:100px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div></div><div style=\"width:100px;height:100px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/block-100pct-width",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100%;height:50px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100%;height:50px;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/background-color-body",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0;background:red;\"><div style=\"width:100px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0;background:red;\"><div style=\"width:100px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/inline-block-width-height",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><span style=\"display:inline-block;width:100px;height:50px;background:red;\"></span><span style=\"display:inline-block;width:100px;height:50px;background:blue;\"></span></body></html>",
        ref_html: "<html><body style=\"margin:0\"><span style=\"display:inline-block;width:100px;height:50px;background:red;\"></span><span style=\"display:inline-block;width:100px;height:50px;background:blue;\"></span></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/table-cell-basic",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:50px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:50px;background:blue;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:50px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:50px;background:blue;\"></div></div></div></body></html>",
        is_match: true,
    },
    // ── 13-16: display:block behavior and block formatting ──
    InlineReftestDef {
        id: "css-display/block-stacking",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"height:40px;background:red;\"></div><div style=\"height:40px;background:blue;\"></div><div style=\"height:40px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"height:40px;background:red;\"></div><div style=\"height:40px;background:blue;\"></div><div style=\"height:40px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/block-margin-collapse",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"height:40px;background:red;\"></div><div style=\"margin-top:20px;height:40px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"height:40px;background:red;\"></div><div style=\"margin-top:20px;height:40px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/block-fixed-width-centering",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;margin:0 auto;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;margin:0 auto;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/block-contains-inline",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;background:#eee;\">hello world</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;background:#eee;\">hello world</div></body></html>",
        is_match: true,
    },
    // ── 17-22: display:inline-block sizing and alignment ──
    InlineReftestDef {
        id: "css-display/inline-block-baseline-align",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:50px;height:100px;background:red;\"></div><div style=\"display:inline-block;width:50px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:50px;height:100px;background:red;\"></div><div style=\"display:inline-block;width:50px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/inline-block-vertical-align-top",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;vertical-align:top;width:50px;height:100px;background:red;\"></div><div style=\"display:inline-block;vertical-align:top;width:50px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;vertical-align:top;width:50px;height:100px;background:red;\"></div><div style=\"display:inline-block;vertical-align:top;width:50px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/inline-block-line-wrap",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:120px;\"><div style=\"display:inline-block;width:60px;height:40px;background:red;\"></div><div style=\"display:inline-block;width:60px;height:40px;background:blue;\"></div><div style=\"display:inline-block;width:60px;height:40px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:120px;\"><div style=\"display:inline-block;width:60px;height:40px;background:red;\"></div><div style=\"display:inline-block;width:60px;height:40px;background:blue;\"></div><div style=\"display:inline-block;width:60px;height:40px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/inline-block-no-width-shrink-to-fit",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;background:red;\">short</div><div style=\"display:inline-block;background:blue;\">a longer text here</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;background:red;\">short</div><div style=\"display:inline-block;background:blue;\">a longer text here</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/inline-block-padding",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;padding:10px;background:red;\">text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;padding:10px;background:red;\">text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/inline-block-with-explicit-size",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:80px;height:60px;background:red;\"></div><div style=\"display:inline-block;width:80px;height:60px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:80px;height:60px;background:red;\"></div><div style=\"display:inline-block;width:80px;height:60px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    // ── 23-26: display:none removing elements from layout ──
    InlineReftestDef {
        id: "css-display/none-on-span",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><span style=\"display:none;\">hidden</span><span>visible</span></body></html>",
        ref_html: "<html><body style=\"margin:0\"><span>visible</span></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/none-nested-child",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:none;\"><div style=\"width:100px;height:100px;background:red;\"></div></div><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/none-sibling-no-gap",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"height:30px;background:red;\"></div><div style=\"display:none;height:30px;background:blue;\"></div><div style=\"height:30px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"height:30px;background:red;\"></div><div style=\"height:30px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/none-toggle-visibility",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:none;height:50px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:none;height:50px;background:red;\"></div></body></html>",
        is_match: true,
    },
    // ── 27-29: visibility:hidden vs display:none ──
    InlineReftestDef {
        id: "css-display/visibility-hidden-vs-none",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"height:50px;background:red;\"></div><div style=\"visibility:hidden;height:50px;background:blue;\"></div><div style=\"height:50px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"height:50px;background:red;\"></div><div style=\"height:50px;background:green;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-display/visibility-hidden-keeps-space-inline-block",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:80px;height:40px;background:red;\"></div><div style=\"display:inline-block;visibility:hidden;width:80px;height:40px;background:blue;\"></div><div style=\"display:inline-block;width:80px;height:40px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:inline-block;width:80px;height:40px;background:red;\"></div><div style=\"display:inline-block;visibility:hidden;width:80px;height:40px;background:blue;\"></div><div style=\"display:inline-block;width:80px;height:40px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/visibility-collapse-vs-hidden",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"height:50px;background:red;\"></div><div style=\"visibility:collapse;height:50px;background:blue;\"></div><div style=\"height:50px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"height:50px;background:red;\"></div><div style=\"visibility:collapse;height:50px;background:blue;\"></div><div style=\"height:50px;background:green;\"></div></body></html>",
        is_match: true,
    },
    // ── 30-34: display:flex variations ──
    InlineReftestDef {
        id: "css-display/flex-direction-row",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:row;width:200px;height:50px;\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:row;width:200px;height:50px;\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/flex-direction-column",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;width:100px;height:100px;\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;width:100px;height:100px;\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/flex-wrap-wrap",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-wrap:wrap;width:100px;\"><div style=\"width:60px;height:30px;background:red;\"></div><div style=\"width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-wrap:wrap;width:100px;\"><div style=\"width:60px;height:30px;background:red;\"></div><div style=\"width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/flex-justify-space-between",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;justify-content:space-between;width:200px;height:50px;\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;justify-content:space-between;width:200px;height:50px;\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/flex-align-items-center",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;align-items:center;width:200px;height:100px;\"><div style=\"width:50px;height:30px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;align-items:center;width:200px;height:100px;\"><div style=\"width:50px;height:30px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 35-39: display:grid variations ──
    InlineReftestDef {
        id: "css-display/grid-template-columns-2col",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div><div style=\"background:green;\"></div><div style=\"background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;width:200px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div><div style=\"background:green;\"></div><div style=\"background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/grid-template-rows-2row",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:50px 50px;width:100px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:50px 50px;width:100px;height:100px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/grid-gap",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;gap:10px;width:210px;\"><div style=\"height:50px;background:red;\"></div><div style=\"height:50px;background:blue;\"></div><div style=\"height:50px;background:green;\"></div><div style=\"height:50px;background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;gap:10px;width:210px;\"><div style=\"height:50px;background:red;\"></div><div style=\"height:50px;background:blue;\"></div><div style=\"height:50px;background:green;\"></div><div style=\"height:50px;background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/grid-column-span",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;\"><div style=\"grid-column:span 2;height:50px;background:red;\"></div><div style=\"height:50px;background:blue;\"></div><div style=\"height:50px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;\"><div style=\"grid-column:span 2;height:50px;background:red;\"></div><div style=\"height:50px;background:blue;\"></div><div style=\"height:50px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/grid-row-span",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:50px 50px;grid-template-columns:100px 100px;width:200px;height:100px;\"><div style=\"grid-row:span 2;background:red;\"></div><div style=\"background:blue;\"></div><div style=\"background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:50px 50px;grid-template-columns:100px 100px;width:200px;height:100px;\"><div style=\"grid-row:span 2;background:red;\"></div><div style=\"background:blue;\"></div><div style=\"background:green;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 40-42: nested display types: flex in grid, grid in flex ──
    InlineReftestDef {
        id: "css-display/grid-containing-flex",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:100px;\"><div style=\"display:flex;\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div><div style=\"background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:100px;\"><div style=\"display:flex;\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div><div style=\"background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/flex-containing-grid",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:100px;\"><div style=\"height:50px;background:red;\"></div><div style=\"height:50px;background:blue;\"></div></div><div style=\"flex:1;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:100px;\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:100px;\"><div style=\"height:50px;background:red;\"></div><div style=\"height:50px;background:blue;\"></div></div><div style=\"flex:1;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/nested-inline-block-in-flex",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:60px;\"><div style=\"display:inline-block;width:60px;height:60px;background:red;\"></div><div style=\"display:inline-block;width:60px;height:60px;background:blue;\"></div><div style=\"display:inline-block;width:60px;height:60px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:60px;\"><div style=\"display:inline-block;width:60px;height:60px;background:red;\"></div><div style=\"display:inline-block;width:60px;height:60px;background:blue;\"></div><div style=\"display:inline-block;width:60px;height:60px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 43-47: display:table, table-row, table-cell ──
    InlineReftestDef {
        id: "css-display/table-two-rows",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:40px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:blue;\"></div></div><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:40px;background:green;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:yellow;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:40px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:blue;\"></div></div><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:40px;background:green;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:yellow;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/table-cell-padding",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;padding:10px;background:red;\">A</div><div style=\"display:table-cell;padding:10px;background:blue;\">B</div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;padding:10px;background:red;\">A</div><div style=\"display:table-cell;padding:10px;background:blue;\">B</div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/table-cell-vertical-align-middle",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;height:80px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;vertical-align:middle;background:red;\">A</div><div style=\"display:table-cell;vertical-align:middle;background:blue;\">B</div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;height:80px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;vertical-align:middle;background:red;\">A</div><div style=\"display:table-cell;vertical-align:middle;background:blue;\">B</div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/table-fixed-layout",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:table;table-layout:fixed;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:40px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:blue;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:table;table-layout:fixed;width:200px;\"><div style=\"display:table-row;\"><div style=\"display:table-cell;width:100px;height:40px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:blue;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/table-no-row-direct-cells",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-cell;width:100px;height:40px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:table;width:200px;\"><div style=\"display:table-cell;width:100px;height:40px;background:red;\"></div><div style=\"display:table-cell;width:100px;height:40px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 48-50: mismatch cases: different display values produce different visuals ──
    InlineReftestDef {
        id: "css-display/block-stacking-vertical",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:block;width:100px;height:50px;background:red;\"></div><div style=\"display:block;width:100px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:block;width:100px;height:50px;background:red;\"></div><div style=\"display:block;width:100px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-display/flex-row-vs-column-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:row;width:100px;height:100px;\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;width:100px;height:100px;\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-display/grid-vs-flex-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:50px;\"><div style=\"background:red;\"></div><div style=\"background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:50px;\"><div style=\"flex:1;background:red;\"></div><div style=\"flex:1;background:blue;\"></div></div></body></html>",
        is_match: false,
    },
];

pub fn reftests() -> &'static [InlineReftestDef] {
    REFTESTS
}
