use super::InlineReftestDef;
use crate::reftest::ReftestCategory;

const REFTESTS: &[InlineReftestDef] = &[
    // ── 180-189: Float 布局 (original 10) ──
    InlineReftestDef {
        id: "css-float/left-basic",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/right-basic",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:right;width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:right;width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/two-left-stacked",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div><div style=\"width:50px;height:50px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div><div style=\"width:50px;height:50px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/left-and-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"float:right;width:50px;height:50px;background:blue;\"></div><div style=\"width:50px;height:50px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"float:right;width:50px;height:50px;background:blue;\"></div><div style=\"width:50px;height:50px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/left-vs-right-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:right;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-float/nested-float",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;\"><div style=\"float:left;width:100px;height:100px;background:red;\"><div style=\"float:left;width:30px;height:30px;background:blue;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;\"><div style=\"float:left;width:100px;height:100px;background:red;\"><div style=\"float:left;width:30px;height:30px;background:blue;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/float-with-margin",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin:10px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin:10px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/float-none-no-float",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:none;width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/float-in-flex",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:50px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"flex:1;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;width:200px;height:50px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"flex:1;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/float-in-grid",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:50px;\"><div style=\"float:left;width:30px;height:30px;background:red;\"></div><div style=\"background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;height:50px;\"><div style=\"float:left;width:30px;height:30px;background:red;\"></div><div style=\"background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Multiple left floats stacking horizontally (5 cases) ──
    InlineReftestDef {
        id: "css-float/three-left-horizontal",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:60px;height:60px;background:red;\"></div><div style=\"float:left;width:60px;height:60px;background:blue;\"></div><div style=\"float:left;width:60px;height:60px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:60px;height:60px;background:red;\"></div><div style=\"float:left;width:60px;height:60px;background:blue;\"></div><div style=\"float:left;width:60px;height:60px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/four-left-horizontal",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:left;width:80px;height:50px;background:red;\"></div><div style=\"float:left;width:80px;height:50px;background:blue;\"></div><div style=\"float:left;width:80px;height:50px;background:green;\"></div><div style=\"float:left;width:80px;height:50px;background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:left;width:80px;height:50px;background:red;\"></div><div style=\"float:left;width:80px;height:50px;background:blue;\"></div><div style=\"float:left;width:80px;height:50px;background:green;\"></div><div style=\"float:left;width:80px;height:50px;background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/five-left-horizontal",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:500px;height:100px;\"><div style=\"float:left;width:80px;height:40px;background:red;\"></div><div style=\"float:left;width:80px;height:40px;background:blue;\"></div><div style=\"float:left;width:80px;height:40px;background:green;\"></div><div style=\"float:left;width:80px;height:40px;background:yellow;\"></div><div style=\"float:left;width:80px;height:40px;background:purple;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:500px;height:100px;\"><div style=\"float:left;width:80px;height:40px;background:red;\"></div><div style=\"float:left;width:80px;height:40px;background:blue;\"></div><div style=\"float:left;width:80px;height:40px;background:green;\"></div><div style=\"float:left;width:80px;height:40px;background:yellow;\"></div><div style=\"float:left;width:80px;height:40px;background:purple;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/left-floats-exact-fit",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:100px;height:50px;background:red;\"></div><div style=\"float:left;width:100px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:100px;height:50px;background:red;\"></div><div style=\"float:left;width:100px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Multiple right floats (4 cases) ──
    InlineReftestDef {
        id: "css-float/two-right-stacked",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:right;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:right;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/three-right-horizontal",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:right;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:50px;background:blue;\"></div><div style=\"float:right;width:80px;height:50px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:right;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:50px;background:blue;\"></div><div style=\"float:right;width:80px;height:50px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/right-float-single-wide",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:right;width:200px;height:80px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:right;width:200px;height:80px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Mixed left and right floats (4 cases) ──
    InlineReftestDef {
        id: "css-float/mixed-left-right-two",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:80px;height:60px;background:red;\"></div><div style=\"float:right;width:80px;height:60px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:80px;height:60px;background:red;\"></div><div style=\"float:right;width:80px;height:60px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/mixed-left-right-three",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:left;width:60px;height:50px;background:red;\"></div><div style=\"float:left;width:60px;height:50px;background:green;\"></div><div style=\"float:right;width:60px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:left;width:60px;height:50px;background:red;\"></div><div style=\"float:left;width:60px;height:50px;background:green;\"></div><div style=\"float:right;width:60px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/mixed-both-sides-symmetrical",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"float:right;width:50px;height:50px;background:blue;\"></div><div style=\"float:left;width:50px;height:50px;background:green;\"></div><div style=\"float:right;width:50px;height:50px;background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"float:right;width:50px;height:50px;background:blue;\"></div><div style=\"float:left;width:50px;height:50px;background:green;\"></div><div style=\"float:right;width:50px;height:50px;background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/mixed-left-right-with-block",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:60px;height:60px;background:red;\"></div><div style=\"float:right;width:60px;height:60px;background:blue;\"></div><div style=\"width:60px;height:30px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:60px;height:60px;background:red;\"></div><div style=\"float:right;width:60px;height:60px;background:blue;\"></div><div style=\"width:60px;height:30px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Float with clear (5 cases) ──
    InlineReftestDef {
        id: "css-float/clear-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:30px;background:red;\"></div><div style=\"float:left;clear:left;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:30px;background:red;\"></div><div style=\"float:left;clear:left;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/clear-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:right;width:60px;height:30px;background:red;\"></div><div style=\"float:right;clear:right;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:right;width:60px;height:30px;background:red;\"></div><div style=\"float:right;clear:right;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/clear-both-left-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:30px;background:red;\"></div><div style=\"float:right;width:60px;height:30px;background:green;\"></div><div style=\"float:left;clear:both;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:30px;background:red;\"></div><div style=\"float:right;width:60px;height:30px;background:green;\"></div><div style=\"float:left;clear:both;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/clear-left-after-two-lefts",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:40px;background:red;\"></div><div style=\"float:left;width:60px;height:40px;background:green;\"></div><div style=\"float:left;clear:left;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:40px;background:red;\"></div><div style=\"float:left;width:60px;height:40px;background:green;\"></div><div style=\"float:left;clear:left;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/clear-both-after-stacked",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:30px;background:green;\"></div><div style=\"float:left;clear:both;width:80px;height:40px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:30px;background:green;\"></div><div style=\"float:left;clear:both;width:80px;height:40px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Float with different sizes (4 cases) ──
    InlineReftestDef {
        id: "css-float/left-small-large",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:40px;height:40px;background:red;\"></div><div style=\"float:left;width:100px;height:80px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:40px;height:40px;background:red;\"></div><div style=\"float:left;width:100px;height:80px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/left-large-small",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:100px;height:80px;background:red;\"></div><div style=\"float:left;width:40px;height:40px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:100px;height:80px;background:red;\"></div><div style=\"float:left;width:40px;height:40px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/right-different-sizes",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:right;width:50px;height:30px;background:red;\"></div><div style=\"float:right;width:80px;height:60px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:right;width:50px;height:30px;background:red;\"></div><div style=\"float:right;width:80px;height:60px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/mixed-sizes-left-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:200px;\"><div style=\"float:left;width:60px;height:90px;background:red;\"></div><div style=\"float:right;width:100px;height:50px;background:blue;\"></div><div style=\"float:left;width:40px;height:40px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:200px;\"><div style=\"float:left;width:60px;height:90px;background:red;\"></div><div style=\"float:right;width:100px;height:50px;background:blue;\"></div><div style=\"float:left;width:40px;height:40px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Float inside container with overflow:hidden (BFC) (4 cases) ──
    InlineReftestDef {
        id: "css-float/bfc-overflow-hidden-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;overflow:hidden;\"><div style=\"float:left;width:80px;height:80px;background:red;\"></div><div style=\"width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;overflow:hidden;\"><div style=\"float:left;width:80px;height:80px;background:red;\"></div><div style=\"width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/bfc-overflow-hidden-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;overflow:hidden;\"><div style=\"float:right;width:80px;height:80px;background:red;\"></div><div style=\"width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;overflow:hidden;\"><div style=\"float:right;width:80px;height:80px;background:red;\"></div><div style=\"width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/bfc-overflow-hidden-both",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;overflow:hidden;\"><div style=\"float:left;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:50px;background:blue;\"></div><div style=\"width:60px;height:20px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;overflow:hidden;\"><div style=\"float:left;width:80px;height:50px;background:red;\"></div><div style=\"float:right;width:80px;height:50px;background:blue;\"></div><div style=\"width:60px;height:20px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/bfc-overflow-hidden-stacked",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;overflow:hidden;\"><div style=\"float:left;width:60px;height:60px;background:red;\"></div><div style=\"float:left;width:60px;height:60px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;overflow:hidden;\"><div style=\"float:left;width:60px;height:60px;background:red;\"></div><div style=\"float:left;width:60px;height:60px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Float with margin and padding interactions (4 cases) ──
    InlineReftestDef {
        id: "css-float/left-margin-20",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin-left:20px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin-left:20px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/right-margin-20",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:right;width:50px;height:50px;margin-right:20px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:right;width:50px;height:50px;margin-right:20px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/left-with-padding",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;padding:10px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;padding:10px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/left-margin-padding-combined",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin:10px;padding:5px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin:10px;padding:5px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Float wrapping behavior when not enough space (4 cases) ──
    InlineReftestDef {
        id: "css-float/wrap-to-next-line",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:150px;height:200px;\"><div style=\"float:left;width:80px;height:40px;background:red;\"></div><div style=\"float:left;width:80px;height:40px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:150px;height:200px;\"><div style=\"float:left;width:80px;height:40px;background:red;\"></div><div style=\"float:left;width:80px;height:40px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/wrap-right-under-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:150px;height:200px;\"><div style=\"float:left;width:100px;height:60px;background:red;\"></div><div style=\"float:right;width:80px;height:40px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:150px;height:200px;\"><div style=\"float:left;width:100px;height:60px;background:red;\"></div><div style=\"float:right;width:80px;height:40px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/wrap-three-in-narrow",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:300px;\"><div style=\"float:left;width:80px;height:40px;background:red;\"></div><div style=\"float:left;width:80px;height:40px;background:blue;\"></div><div style=\"float:left;width:80px;height:40px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:300px;\"><div style=\"float:left;width:80px;height:40px;background:red;\"></div><div style=\"float:left;width:80px;height:40px;background:blue;\"></div><div style=\"float:left;width:80px;height:40px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    // ── Nested floats (float inside float) (4 cases) ──
    InlineReftestDef {
        id: "css-float/nested-left-in-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:150px;height:100px;background:red;\"><div style=\"float:left;width:50px;height:50px;background:blue;\"></div><div style=\"float:left;width:50px;height:50px;background:green;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:150px;height:100px;background:red;\"><div style=\"float:left;width:50px;height:50px;background:blue;\"></div><div style=\"float:left;width:50px;height:50px;background:green;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/nested-right-in-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:right;width:150px;height:100px;background:red;\"><div style=\"float:right;width:50px;height:50px;background:blue;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:right;width:150px;height:100px;background:red;\"><div style=\"float:right;width:50px;height:50px;background:blue;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/nested-mixed-in-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:200px;height:100px;background:red;\"><div style=\"float:left;width:40px;height:40px;background:blue;\"></div><div style=\"float:right;width:40px;height:40px;background:green;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:200px;height:100px;background:red;\"><div style=\"float:left;width:40px;height:40px;background:blue;\"></div><div style=\"float:right;width:40px;height:40px;background:green;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/nested-two-levels",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:300px;\"><div style=\"float:left;width:200px;height:150px;background:red;\"><div style=\"float:left;width:100px;height:80px;background:blue;\"><div style=\"float:left;width:40px;height:40px;background:green;\"></div></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:400px;height:300px;\"><div style=\"float:left;width:200px;height:150px;background:red;\"><div style=\"float:left;width:100px;height:80px;background:blue;\"><div style=\"float:left;width:40px;height:40px;background:green;\"></div></div></div></div></body></html>",
        is_match: true,
    },
    // ── Mismatch cases: float vs no-float, left vs right (5 cases) ──
    InlineReftestDef {
        id: "css-float/float-left-with-block-beside",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:left;width:50px;height:50px;background:red;\"></div><div style=\"width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/left-vs-right-two-floats-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:60px;height:50px;background:red;\"></div><div style=\"float:left;width:60px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:right;width:60px;height:50px;background:red;\"></div><div style=\"float:right;width:60px;height:50px;background:blue;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-float/float-none-block-behavior",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:none;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"float:none;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/clear-left-stacking",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:30px;background:red;\"></div><div style=\"float:left;clear:left;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:200px;\"><div style=\"float:left;width:60px;height:30px;background:red;\"></div><div style=\"float:left;clear:left;width:60px;height:30px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-float/float-with-margin-20px",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin:20px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;\"><div style=\"float:left;width:50px;height:50px;margin:20px;background:red;\"></div><div style=\"float:left;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
];

pub fn reftests() -> &'static [InlineReftestDef] {
    REFTESTS
}
