use super::InlineReftestDef;
use crate::reftest::ReftestCategory;

const REFTESTS: &[InlineReftestDef] = &[
    // ── 1. writing-mode: horizontal-tb (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/horizontal-tb-default",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;\">Hello World</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;\">Hello World</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/horizontal-tb-multiline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;width:100px;\">AB CD EF GH</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;width:100px;\">AB CD EF GH</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/horizontal-tb-with-inline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;\"><span>A</span><span>B</span><span>C</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;\"><span>A</span><span>B</span><span>C</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/horizontal-tb-nested-divs",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;\"><div>Inner A</div><div>Inner B</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;\"><div>Inner A</div><div>Inner B</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/horizontal-tb-with-padding",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;padding:10px;\">Padded</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;padding:10px;\">Padded</div></body></html>",
        is_match: true,
    },
    // ── 2. writing-mode: vertical-rl (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-basic",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;\">ABC</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;\">ABC</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-multiline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;height:80px;\">AB CD EF</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;height:80px;\">AB CD EF</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-with-spans",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;\"><span>X</span><span>Y</span><span>Z</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;\"><span>X</span><span>Y</span><span>Z</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-nested-blocks",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;\"><div>Col A</div><div>Col B</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;\"><div>Col A</div><div>Col B</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-with-margin",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;margin:10px;\">Margin</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;margin:10px;\">Margin</div></body></html>",
        is_match: true,
    },
    // ── 3. writing-mode: vertical-lr (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/vertical-lr-basic",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;\">ABC</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;\">ABC</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-lr-multiline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;height:80px;\">AB CD EF</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;height:80px;\">AB CD EF</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-lr-with-spans",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;\"><span>P</span><span>Q</span><span>R</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;\"><span>P</span><span>Q</span><span>R</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-lr-nested-blocks",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;\"><div>Block 1</div><div>Block 2</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;\"><div>Block 1</div><div>Block 2</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-lr-with-padding",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;padding:8px;\">Pad LR</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;padding:8px;\">Pad LR</div></body></html>",
        is_match: true,
    },
    // ── 4. direction: ltr, rtl (6 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/direction-ltr-basic",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"direction:ltr;\">Hello LTR</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"direction:ltr;\">Hello LTR</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/direction-rtl-basic",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"direction:rtl;\">Hello RTL</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"direction:rtl;\">Hello RTL</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/direction-ltr-text-align",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"direction:ltr;text-align:right;width:200px;\">Right in LTR</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"direction:ltr;text-align:right;width:200px;\">Right in LTR</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/direction-rtl-text-align",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"direction:rtl;text-align:left;width:200px;\">Left in RTL</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"direction:rtl;text-align:left;width:200px;\">Left in RTL</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/direction-ltr-inline-sequence",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"direction:ltr;\"><span>A</span><span>B</span><span>C</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"direction:ltr;\"><span>A</span><span>B</span><span>C</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/direction-rtl-inline-sequence",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"direction:rtl;\"><span>A</span><span>B</span><span>C</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"direction:rtl;\"><span>A</span><span>B</span><span>C</span></div></body></html>",
        is_match: true,
    },
    // ── 5. unicode-bidi: normal, embed, bidi-override (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/unicode-bidi-normal",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:normal;\">Normal bidi</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:normal;\">Normal bidi</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/unicode-bidi-embed-ltr",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:embed;direction:ltr;\">Embed LTR</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:embed;direction:ltr;\">Embed LTR</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/unicode-bidi-embed-rtl",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:embed;direction:rtl;\">Embed RTL</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:embed;direction:rtl;\">Embed RTL</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/unicode-bidi-bidi-override-ltr",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:bidi-override;direction:ltr;\">Override LTR</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:bidi-override;direction:ltr;\">Override LTR</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/unicode-bidi-bidi-override-rtl",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:bidi-override;direction:rtl;\">Override RTL</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"unicode-bidi:bidi-override;direction:rtl;\">Override RTL</div></body></html>",
        is_match: true,
    },
    // https://www.unicode.org/reports/tr9/#P1
    InlineReftestDef {
        id: "css-writing-modes/bidi-multi-paragraph-rtl",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"white-space:pre;font-size:64px;line-height:80px\">אבגאבגאבגאבגאבג\nדהודהודהודהודהו</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-size:64px;line-height:80px\">אבגאבגאבגאבגאבג</div><div style=\"font-size:64px;line-height:80px\">דהודהודהודהודהו</div></body></html>",
        is_match: true,
    },
    // ── 6. text-orientation: mixed, upright, sideways (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/text-orientation-mixed",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;text-orientation:mixed;\">ABC</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;text-orientation:mixed;\">ABC</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/text-orientation-upright",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;text-orientation:upright;\">ABC</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;text-orientation:upright;\">ABC</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/text-orientation-sideways",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;text-orientation:sideways;\">ABC</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;text-orientation:sideways;\">ABC</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/text-orientation-mixed-vertical-lr",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;text-orientation:mixed;\">XYZ</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;text-orientation:mixed;\">XYZ</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/text-orientation-upright-vertical-lr",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;text-orientation:upright;\">XYZ</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;text-orientation:upright;\">XYZ</div></body></html>",
        is_match: true,
    },
    // ── 7. writing-mode in flex containers (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/flex-horizontal-tb-child",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><div style=\"writing-mode:horizontal-tb;\">Flex H</div><div>Item</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><div style=\"writing-mode:horizontal-tb;\">Flex H</div><div>Item</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/flex-vertical-rl-child",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><div style=\"writing-mode:vertical-rl;\">Flex V</div><div>Item</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><div style=\"writing-mode:vertical-rl;\">Flex V</div><div>Item</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/flex-vertical-lr-child",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><div style=\"writing-mode:vertical-lr;\">Flex VL</div><div>Item</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><div style=\"writing-mode:vertical-lr;\">Flex VL</div><div>Item</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/flex-row-writing-mode",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:row;width:200px;\"><div style=\"writing-mode:vertical-rl;\">A</div><div style=\"writing-mode:horizontal-tb;\">B</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:row;width:200px;\"><div style=\"writing-mode:vertical-rl;\">A</div><div style=\"writing-mode:horizontal-tb;\">B</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/flex-column-writing-mode",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;height:100px;\"><div style=\"writing-mode:vertical-rl;\">R1</div><div style=\"writing-mode:horizontal-tb;\">R2</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;height:100px;\"><div style=\"writing-mode:vertical-rl;\">R1</div><div style=\"writing-mode:horizontal-tb;\">R2</div></div></body></html>",
        is_match: true,
    },
    // ── 8. writing-mode in grid containers (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/grid-horizontal-tb-cell",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;\"><div style=\"writing-mode:horizontal-tb;\">Cell A</div><div>Cell B</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;\"><div style=\"writing-mode:horizontal-tb;\">Cell A</div><div>Cell B</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/grid-vertical-rl-cell",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;\"><div style=\"writing-mode:vertical-rl;\">Cell V</div><div>Cell H</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;width:200px;\"><div style=\"writing-mode:vertical-rl;\">Cell V</div><div>Cell H</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/grid-vertical-lr-cell",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;\"><div style=\"writing-mode:vertical-lr;\">LR A</div><div style=\"writing-mode:vertical-lr;\">LR B</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:100px 100px;\"><div style=\"writing-mode:vertical-lr;\">LR A</div><div style=\"writing-mode:vertical-lr;\">LR B</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/grid-mixed-writing-modes",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:50px 50px;width:200px;\"><div style=\"writing-mode:horizontal-tb;\">Row H</div><div style=\"writing-mode:vertical-rl;\">Row V</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:50px 50px;width:200px;\"><div style=\"writing-mode:horizontal-tb;\">Row H</div><div style=\"writing-mode:vertical-rl;\">Row V</div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/grid-writing-mode-with-gap",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:80px 80px;gap:10px;width:200px;\"><div style=\"writing-mode:vertical-rl;\">G1</div><div style=\"writing-mode:horizontal-tb;\">G2</div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:80px 80px;gap:10px;width:200px;\"><div style=\"writing-mode:vertical-rl;\">G1</div><div style=\"writing-mode:horizontal-tb;\">G2</div></div></body></html>",
        is_match: true,
    },
    // ── 9. Combination: writing-mode + direction (5 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/horizontal-tb-direction-rtl",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;direction:rtl;width:200px;\">HTB RTL</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;direction:rtl;width:200px;\">HTB RTL</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-direction-ltr",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;direction:ltr;\">VRL LTR</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;direction:ltr;\">VRL LTR</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-direction-rtl",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;direction:rtl;\">VRL RTL</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;direction:rtl;\">VRL RTL</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-lr-direction-ltr",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;direction:ltr;\">VLR LTR</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;direction:ltr;\">VLR LTR</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-lr-direction-rtl",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;direction:rtl;\">VLR RTL</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-lr;direction:rtl;\">VLR RTL</div></body></html>",
        is_match: true,
    },
    // ── 10. writing-mode with sizing: width/height behavior (4 cases) ──
    InlineReftestDef {
        id: "css-writing-modes/horizontal-tb-explicit-size",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;width:150px;height:60px;\">Sized</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:horizontal-tb;width:150px;height:60px;\">Sized</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/vertical-rl-explicit-size",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;width:60px;height:150px;\">Sized V</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;width:60px;height:150px;\">Sized V</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/writing-mode-auto-margin",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;width:100px;height:100px;margin:20px;\">Mrg</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;width:100px;height:100px;margin:20px;\">Mrg</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-writing-modes/writing-mode-border-box",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;width:100px;height:100px;border:5px solid black;padding:10px;\">Box</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"writing-mode:vertical-rl;width:100px;height:100px;border:5px solid black;padding:10px;\">Box</div></body></html>",
        is_match: true,
    },
];

pub fn reftests() -> &'static [InlineReftestDef] {
    REFTESTS
}
