use super::InlineReftestDef;
use crate::reftest::ReftestCategory;

const REFTESTS: &[InlineReftestDef] = &[
    // ── 1. text-decoration-line ──
    InlineReftestDef {
        id: "css-text-decor/line-underline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:underline;\">Underlined text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:underline;\">Underlined text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/line-overline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:overline;\">Overlined text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:overline;\">Overlined text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/line-through",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:line-through;\">Struck through text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:line-through;\">Struck through text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/line-none",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:none;\">No decoration</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:none;\">No decoration</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/line-underline-overline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:underline overline;\">Under and over text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:underline overline;\">Under and over text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/line-underline-overline-through",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:underline overline line-through;\">All three lines</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration-line:underline overline line-through;\">All three lines</div></body></html>",
        is_match: true,
    },
    // ── 2. text-decoration-style ──
    InlineReftestDef {
        id: "css-text-decor/style-solid",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline solid;\">Solid underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline solid;\">Solid underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/style-dashed",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline dashed;\">Dashed underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline dashed;\">Dashed underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/style-dotted",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline dotted;\">Dotted underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline dotted;\">Dotted underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/style-double",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline double;\">Double underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline double;\">Double underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/style-wavy",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline wavy;\">Wavy underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline wavy;\">Wavy underline</div></body></html>",
        is_match: true,
    },
    // ── 3. text-decoration-color ──
    InlineReftestDef {
        id: "css-text-decor/color-named-red",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline red;\">Red underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline red;\">Red underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/color-named-blue",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline blue;\">Blue underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline blue;\">Blue underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/color-hex",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline #FF5733;\">Hex color underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline #FF5733;\">Hex color underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/color-rgb",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline rgb(0,128,255);\">RGB underline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline rgb(0,128,255);\">RGB underline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/color-green-line-through",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:line-through green;\">Green strike</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:line-through green;\">Green strike</div></body></html>",
        is_match: true,
    },
    // ── 4. text-decoration shorthand ──
    InlineReftestDef {
        id: "css-text-decor/shorthand-underline-solid-red",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline solid red;\">Shorthand test 1</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline solid red;\">Shorthand test 1</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/shorthand-overline-dashed-blue",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:overline dashed blue;\">Shorthand test 2</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:overline dashed blue;\">Shorthand test 2</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/shorthand-through-dotted-green",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:line-through dotted green;\">Shorthand test 3</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:line-through dotted green;\">Shorthand test 3</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/shorthand-underline-wavy-orange",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline wavy orange;\">Shorthand test 4</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline wavy orange;\">Shorthand test 4</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/shorthand-underline-double-purple",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline double purple;\">Shorthand test 5</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline double purple;\">Shorthand test 5</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/shorthand-none",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:none;\">No decoration shorthand</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:none;\">No decoration shorthand</div></body></html>",
        is_match: true,
    },
    // ── 5. text-decoration with different font sizes ──
    InlineReftestDef {
        id: "css-text-decor/font-size-small",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"font-size:10px;text-decoration:underline;\">Small text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-size:10px;text-decoration:underline;\">Small text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/font-size-large",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"font-size:32px;text-decoration:underline;\">Large text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-size:32px;text-decoration:underline;\">Large text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/font-size-xl-line-through",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"font-size:48px;text-decoration:line-through;\">XL text strike</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-size:48px;text-decoration:line-through;\">XL text strike</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/font-size-xxs-overline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"font-size:8px;text-decoration:overline;\">Tiny overline</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-size:8px;text-decoration:overline;\">Tiny overline</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/font-size-mixed-decoration",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"font-size:24px;text-decoration:underline overline;\">Big both lines</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"font-size:24px;text-decoration:underline overline;\">Big both lines</div></body></html>",
        is_match: true,
    },
    // ── 6. text-decoration in flex containers ──
    InlineReftestDef {
        id: "css-text-decor/flex-underline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><span style=\"text-decoration:underline;\">Flex item</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><span style=\"text-decoration:underline;\">Flex item</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/flex-line-through-multiple",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><span style=\"text-decoration:line-through;\">A</span><span style=\"text-decoration:line-through;\">B</span><span style=\"text-decoration:line-through;\">C</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><span style=\"text-decoration:line-through;\">A</span><span style=\"text-decoration:line-through;\">B</span><span style=\"text-decoration:line-through;\">C</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/flex-column-overline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;\"><span style=\"text-decoration:overline;\">Row 1</span><span style=\"text-decoration:overline;\">Row 2</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;flex-direction:column;\"><span style=\"text-decoration:overline;\">Row 1</span><span style=\"text-decoration:overline;\">Row 2</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/flex-wavy-colored",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><span style=\"text-decoration:underline wavy red;\">Wavy red</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;\"><span style=\"text-decoration:underline wavy red;\">Wavy red</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/flex-mixed-decoration",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:flex;gap:10px;\"><span style=\"text-decoration:underline;\">U</span><span style=\"text-decoration:line-through;\">S</span><span style=\"text-decoration:overline;\">O</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:flex;gap:10px;\"><span style=\"text-decoration:underline;\">U</span><span style=\"text-decoration:line-through;\">S</span><span style=\"text-decoration:overline;\">O</span></div></body></html>",
        is_match: true,
    },
    // ── 7. text-decoration in grid containers ──
    InlineReftestDef {
        id: "css-text-decor/grid-underline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;\"><span style=\"text-decoration:underline;\">Grid item</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;\"><span style=\"text-decoration:underline;\">Grid item</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/grid-two-col-line-through",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;\"><span style=\"text-decoration:line-through;\">Col 1</span><span style=\"text-decoration:line-through;\">Col 2</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:1fr 1fr;\"><span style=\"text-decoration:line-through;\">Col 1</span><span style=\"text-decoration:line-through;\">Col 2</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/grid-overline-colored",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;\"><span style=\"text-decoration:overline blue;\">Blue over</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;\"><span style=\"text-decoration:overline blue;\">Blue over</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/grid-dashed-decoration",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:auto auto;\"><span style=\"text-decoration:underline dashed;\">A</span><span style=\"text-decoration:underline dashed;\">B</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-columns:auto auto;\"><span style=\"text-decoration:underline dashed;\">A</span><span style=\"text-decoration:underline dashed;\">B</span></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/grid-mixed-lines",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:auto auto;\"><span style=\"text-decoration:underline overline;\">R1</span><span style=\"text-decoration:line-through;\">R2</span></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"display:grid;grid-template-rows:auto auto;\"><span style=\"text-decoration:underline overline;\">R1</span><span style=\"text-decoration:line-through;\">R2</span></div></body></html>",
        is_match: true,
    },
    // ── 8. text-decoration-skip ──
    InlineReftestDef {
        id: "css-text-decor/skip-none",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-decoration-skip:none;\">Skip none text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-decoration-skip:none;\">Skip none text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/skip-auto",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-decoration-skip:auto;\">Skip auto text</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-decoration-skip:auto;\">Skip auto text</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/skip-none-line-through",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:line-through;text-decoration-skip:none;\">Skip none strike</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:line-through;text-decoration-skip:none;\">Skip none strike</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/skip-auto-overline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:overline;text-decoration-skip:auto;\">Skip auto over</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:overline;text-decoration-skip:auto;\">Skip auto over</div></body></html>",
        is_match: true,
    },
    // ── 9. text-underline-offset ──
    InlineReftestDef {
        id: "css-text-decor/underline-offset-zero",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:0;\">Offset zero</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:0;\">Offset zero</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/underline-offset-4px",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:4px;\">Offset 4px</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:4px;\">Offset 4px</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/underline-offset-8px",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:8px;\">Offset 8px</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:8px;\">Offset 8px</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/underline-offset-negative",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:-2px;\">Negative offset</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;text-underline-offset:-2px;\">Negative offset</div></body></html>",
        is_match: true,
    },
    // ── 10. text-decoration with multiline text ──
    InlineReftestDef {
        id: "css-text-decor/multiline-underline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:120px;text-decoration:underline;\">This is a multiline text with underline that wraps to multiple lines.</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:120px;text-decoration:underline;\">This is a multiline text with underline that wraps to multiple lines.</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/multiline-line-through",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:120px;text-decoration:line-through;\">This is a multiline text with line-through that wraps across lines.</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:120px;text-decoration:line-through;\">This is a multiline text with line-through that wraps across lines.</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/multiline-overline",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;text-decoration:overline;\">Overlined multiline text that wraps to several lines.</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;text-decoration:overline;\">Overlined multiline text that wraps to several lines.</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/multiline-wavy-colored",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;text-decoration:underline wavy red;\">Wavy red multiline text that should wrap across multiple lines.</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;text-decoration:underline wavy red;\">Wavy red multiline text that should wrap across multiple lines.</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-text-decor/multiline-br-lines",
        category: ReftestCategory::Text,
        test_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;\">Line one<br>Line two<br>Line three</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"text-decoration:underline;\">Line one<br>Line two<br>Line three</div></body></html>",
        is_match: true,
    },
];

pub fn reftests() -> &'static [InlineReftestDef] {
    REFTESTS
}
