use super::InlineReftestDef;
use crate::reftest::ReftestCategory;

const REFTESTS: &[InlineReftestDef] = &[
    // ── 96-105: 盒模型进阶 (original 11) ──
    InlineReftestDef {
        id: "css-box/margin-collapse-siblings",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:20px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:10px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:20px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:10px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/padding-box-sizing",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:10px;box-sizing:border-box;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:10px;box-sizing:border-box;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/border-solid-colors",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border-top:10px solid red;border-right:10px solid green;border-bottom:10px solid blue;border-left:10px solid yellow;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border-top:10px solid red;border-right:10px solid green;border-bottom:10px solid blue;border-left:10px solid yellow;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/overflow-hidden-clips",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:hidden;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:hidden;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/overflow-visible-no-clip",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:visible;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:visible;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/max-width-constraint",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:500px;max-width:200px;height:50px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:500px;max-width:200px;height:50px;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/min-height-expands",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;min-height:200px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;min-height:200px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/percentage-width",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"width:50%;height:100%;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;\"><div style=\"width:50%;height:100%;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/auto-margin-center",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;margin-left:auto;margin-right:auto;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;margin-left:auto;margin-right:auto;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/negative-margin-overlap",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:-20px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:-20px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/box-sizing-border-box",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:10px;border:5px solid black;box-sizing:border-box;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:10px;border:5px solid black;box-sizing:border-box;background:red;\"></div></body></html>",
        is_match: true,
    },
    // ── 106-144: 盒模型扩展 (39 new entries) ──

    // --- Margin collapse: parent-child, siblings, multiple, zero ---
    InlineReftestDef {
        id: "css-box/margin-collapse-parent-child",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"margin-top:30px;background:red;\"><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"margin-top:30px;background:red;\"><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/margin-collapse-three-siblings",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:30px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:30px;background:green;margin-top:20px;margin-bottom:40px;\"></div><div style=\"width:100px;height:30px;background:blue;margin-top:10px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:30px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:30px;background:green;margin-top:20px;margin-bottom:40px;\"></div><div style=\"width:100px;height:30px;background:blue;margin-top:10px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/margin-collapse-zero-margin",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:0px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:0px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:0px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:0px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/margin-collapse-negative-positive",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:-10px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:-10px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/margin-collapse-nested-prevented-by-padding",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"padding-top:1px;background:red;\"><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"padding-top:1px;background:red;\"><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/margin-collapse-siblings-equal",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:25px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:25px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:25px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:25px;\"></div></body></html>",
        is_match: true,
    },
    // --- Box-sizing: content-box vs border-box ---
    InlineReftestDef {
        id: "css-box/content-box-with-padding",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:10px;box-sizing:content-box;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:10px;box-sizing:content-box;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/border-box-with-padding-border",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:120px;height:70px;padding:10px;border:5px solid black;box-sizing:border-box;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:120px;height:70px;padding:10px;border:5px solid black;box-sizing:border-box;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/content-box-with-border",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;border:10px solid red;box-sizing:content-box;background:yellow;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;border:10px solid red;box-sizing:content-box;background:yellow;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/border-box-vs-content-box-same-visual",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:120px;height:70px;padding:10px;border:5px solid black;box-sizing:border-box;background:orange;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:10px;border:5px solid black;box-sizing:content-box;background:orange;\"></div></body></html>",
        is_match: true,
    },
    // --- Padding: individual sides, percentage ---
    InlineReftestDef {
        id: "css-box/padding-individual-sides",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;padding-top:10px;padding-right:20px;padding-bottom:30px;padding-left:40px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;padding-top:10px;padding-right:20px;padding-bottom:30px;padding-left:40px;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/padding-percentage-width",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:red;\"><div style=\"width:100px;height:50px;padding:10%;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:red;\"><div style=\"width:100px;height:50px;padding:10%;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/padding-shorthand-vertical-horizontal",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;padding:10px 20px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;padding:10px 20px;background:green;\"></div></body></html>",
        is_match: true,
    },
    // --- Border: different widths per side, border with background ---
    InlineReftestDef {
        id: "css-box/border-different-widths",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border-top:5px solid red;border-right:10px solid green;border-bottom:15px solid blue;border-left:20px solid yellow;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border-top:5px solid red;border-right:10px solid green;border-bottom:15px solid blue;border-left:20px solid yellow;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/border-with-background",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:10px solid black;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:10px solid black;background:red;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/border-uniform-width",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border:10px solid purple;background:yellow;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:80px;border:10px solid purple;background:yellow;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/border-no-shrink-content-box",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;border:5px solid red;box-sizing:content-box;background:lime;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;border:5px solid red;box-sizing:content-box;background:lime;\"></div></body></html>",
        is_match: true,
    },
    // --- Width/Height: auto, percentage, max/min constraints ---
    InlineReftestDef {
        id: "css-box/width-auto-fills-parent",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:red;\"><div style=\"height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:100px;background:red;\"><div style=\"height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/percentage-height-with-parent",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:200px;background:red;\"><div style=\"width:100%;height:50%;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:200px;background:red;\"><div style=\"width:100%;height:50%;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/max-height-shrinks",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:200px;max-height:100px;background:orange;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:200px;max-height:100px;background:orange;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/min-width-expands",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;min-width:150px;height:50px;background:teal;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;min-width:150px;height:50px;background:teal;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/max-width-larger-than-width-no-effect",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;max-width:300px;height:50px;background:navy;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;max-width:300px;height:50px;background:navy;\"></div></body></html>",
        is_match: true,
    },
    // --- Overflow: hidden, visible, scroll, auto with clipping ---
    InlineReftestDef {
        id: "css-box/overflow-scroll-establishes-scrollbar",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:scroll;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:scroll;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/overflow-auto-with-overflow",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:auto;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:auto;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/overflow-auto-no-overflow",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;overflow:auto;background:gray;\"><div style=\"width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;overflow:auto;background:gray;\"><div style=\"width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/overflow-hidden-text-clip",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:20px;overflow:hidden;background:white;\">ABCDEFGHIJKLMNOPQRSTUVWXYZ</div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:20px;overflow:hidden;background:white;\">ABCDEFGHIJKLMNOPQRSTUVWXYZ</div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/overflow-visible-default",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:visible;background:gray;\"><div style=\"width:200px;height:200px;background:rgba(255,0,0,0.5);\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:visible;background:gray;\"><div style=\"width:200px;height:200px;background:rgba(255,0,0,0.5);\"></div></div></body></html>",
        is_match: true,
    },
    // --- Auto margin for centering ---
    InlineReftestDef {
        id: "css-box/auto-margin-center-fixed-width",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:50px;background:red;margin:0 auto;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:50px;background:red;margin:0 auto;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/auto-margin-center-in-container",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;background:gray;\"><div style=\"width:100px;height:50px;margin:0 auto;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:300px;height:100px;background:gray;\"><div style=\"width:100px;height:50px;margin:0 auto;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/auto-margin-right-only",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;margin-left:0;margin-right:auto;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;margin-left:0;margin-right:auto;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/auto-margin-both-horizontal",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:40px;margin-left:auto;margin-right:auto;background:purple;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:80px;height:40px;margin-left:auto;margin-right:auto;background:purple;\"></div></body></html>",
        is_match: true,
    },
    // --- Negative margins: overlap, pull-up ---
    InlineReftestDef {
        id: "css-box/negative-margin-pull-up",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:60px;background:red;\"></div><div style=\"width:100px;height:60px;background:blue;margin-top:-30px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:60px;background:red;\"></div><div style=\"width:100px;height:60px;background:blue;margin-top:-30px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/negative-margin-left-overlap",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-left:-30px;margin-top:0;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-left:-30px;margin-top:0;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/negative-margin-sibling-complete-overlap",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:-50px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:-50px;\"></div></body></html>",
        is_match: true,
    },
    // --- Nested box model: child in parent with padding/border ---
    InlineReftestDef {
        id: "css-box/nested-padding-child-offset",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;padding:20px;background:red;\"><div style=\"width:100px;height:100px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;padding:20px;background:red;\"><div style=\"width:100px;height:100px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/nested-border-child-position",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;border:10px solid black;background:red;\"><div style=\"width:100px;height:100px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;border:10px solid black;background:red;\"><div style=\"width:100px;height:100px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/nested-padding-border-combined",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;padding:15px;border:5px solid black;background:gray;\"><div style=\"width:100px;height:100px;background:orange;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;padding:15px;border:5px solid black;background:gray;\"><div style=\"width:100px;height:100px;background:orange;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/nested-border-box-child-fill",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;padding:20px;border:10px solid black;box-sizing:border-box;background:red;\"><div style=\"width:100%;height:100%;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;padding:20px;border:10px solid black;box-sizing:border-box;background:red;\"><div style=\"width:100%;height:100%;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    // --- Mismatch cases: different box model values produce different visuals ---
    InlineReftestDef {
        id: "css-box/mismatch-content-box-vs-border-box",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:20px;box-sizing:content-box;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;padding:20px;box-sizing:border-box;background:red;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-box/mismatch-overflow-hidden-vs-visible",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:hidden;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;overflow:visible;background:gray;\"><div style=\"width:200px;height:200px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-box/margin-collapse-siblings-30-20",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;margin-bottom:30px;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-box/mismatch-negative-vs-positive-margin",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:-20px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:50px;background:red;\"></div><div style=\"width:100px;height:50px;background:blue;margin-top:20px;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-box/mismatch-different-border-widths",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:5px solid black;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;border:20px solid black;background:red;\"></div></body></html>",
        is_match: false,
    },
];

pub fn reftests() -> &'static [InlineReftestDef] {
    REFTESTS
}
