use super::InlineReftestDef;
use crate::reftest::ReftestCategory;

const REFTESTS: &[InlineReftestDef] = &[
    // ── 76-85: 定位（Positioning） ──
    InlineReftestDef {
        id: "css-position/absolute-top-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:50px;left:50px;width:100px;height:100px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:50px;left:50px;width:100px;height:100px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-shift-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:50px;left:50px;width:100px;height:100px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/relative-offset",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:20px;left:20px;width:100px;height:100px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:20px;left:20px;width:100px;height:100px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/relative-vs-no-position",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:30px;left:30px;width:100px;height:100px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/absolute-in-flow",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"width:100px;height:100px;background:green;\"></div><div style=\"position:absolute;top:0;left:100px;width:100px;height:100px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"width:100px;height:100px;background:green;\"></div><div style=\"position:absolute;top:0;left:100px;width:100px;height:100px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-bottom-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:0;right:0;width:50px;height:50px;background:orange;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:0;right:0;width:50px;height:50px;background:orange;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-stacking-order",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;\"></div><div style=\"position:absolute;top:50px;left:50px;width:100px;height:100px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;\"></div><div style=\"position:absolute;top:50px;left:50px;width:100px;height:100px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/z-index-basic",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:2;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:1;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:2;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:1;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-overlap-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/multiple-relatives",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:50px;background:red;\"></div><div style=\"position:relative;width:100px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:50px;background:red;\"></div><div style=\"position:relative;width:100px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    // ── 200-209: Position + Rendering edge cases ──
    InlineReftestDef {
        id: "css-position/fixed-basic-viewport",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:fixed;top:10px;left:10px;width:50px;height:50px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:fixed;top:10px;left:10px;width:50px;height:50px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-with-margin",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;background:red;\"><div style=\"position:absolute;top:10px;left:10px;margin:5px;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;background:red;\"><div style=\"position:absolute;top:10px;left:10px;margin:5px;width:50px;height:50px;background:blue;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/z-index-negative",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:red;z-index:-1;\"></div><div style=\"width:100px;height:100px;background:blue;margin-top:-50px;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;background:red;z-index:-1;\"></div><div style=\"width:100px;height:100px;background:blue;margin-top:-50px;\"></div></body></html>",
        is_match: true,
    },
    // ── 1. Absolute positioning with various top/left/bottom/right combinations ──
    InlineReftestDef {
        id: "css-position/absolute-top-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:20px;right:20px;width:60px;height:60px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:20px;right:20px;width:60px;height:60px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-bottom-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:30px;left:30px;width:80px;height:80px;background:teal;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:30px;left:30px;width:80px;height:80px;background:teal;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-all-four-offsets",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:10px;left:10px;bottom:10px;right:10px;background:gray;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:10px;left:10px;bottom:10px;right:10px;background:gray;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-top-left-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:10px;left:10px;width:80px;height:80px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:60px;left:60px;width:80px;height:80px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/absolute-centered-with-offsets",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:50px;left:50px;width:100px;height:100px;background:purple;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:50px;left:50px;width:100px;height:100px;background:purple;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-zero-offsets",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;bottom:0;right:0;background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;bottom:0;right:0;background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-large-offsets",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:300px;height:300px;\"><div style=\"position:absolute;top:100px;left:100px;width:100px;height:100px;background:coral;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:300px;height:300px;\"><div style=\"position:absolute;top:100px;left:100px;width:100px;height:100px;background:coral;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-bottom-right-corner",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:0;right:0;width:80px;height:80px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:0;right:0;width:80px;height:80px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-multiple-children",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:60px;height:60px;background:red;\"></div><div style=\"position:absolute;top:0;right:0;width:60px;height:60px;background:green;\"></div><div style=\"position:absolute;bottom:0;left:0;width:60px;height:60px;background:blue;\"></div><div style=\"position:absolute;bottom:0;right:0;width:60px;height:60px;background:yellow;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:60px;height:60px;background:red;\"></div><div style=\"position:absolute;top:0;right:0;width:60px;height:60px;background:green;\"></div><div style=\"position:absolute;bottom:0;left:0;width:60px;height:60px;background:blue;\"></div><div style=\"position:absolute;bottom:0;right:0;width:60px;height:60px;background:yellow;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 2. Relative positioning with positive and negative offsets ──
    InlineReftestDef {
        id: "css-position/relative-positive-top-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:relative;top:40px;left:40px;width:100px;height:100px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:relative;top:40px;left:40px;width:100px;height:100px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/relative-negative-top",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:relative;top:-50px;left:20px;width:100px;height:100px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:relative;top:-50px;left:20px;width:100px;height:100px;background:blue;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/relative-negative-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;left:-30px;width:100px;height:100px;background:green;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;left:-30px;width:100px;height:100px;background:green;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/relative-offset-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:25px;left:25px;width:80px;height:80px;background:orange;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:50px;left:50px;width:80px;height:80px;background:orange;\"></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/relative-right-bottom",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;right:10px;bottom:10px;width:100px;height:100px;background:maroon;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;right:10px;bottom:10px;width:100px;height:100px;background:maroon;\"></div></body></html>",
        is_match: true,
    },
    // ── 3. Fixed positioning (self-match only) ──
    InlineReftestDef {
        id: "css-position/fixed-top-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:fixed;top:0;left:0;width:100px;height:100px;background:navy;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:fixed;top:0;left:0;width:100px;height:100px;background:navy;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/fixed-bottom-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:fixed;bottom:0;right:0;width:80px;height:80px;background:olive;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:fixed;bottom:0;right:0;width:80px;height:80px;background:olive;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/fixed-with-static-sibling",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"position:fixed;top:20px;left:20px;width:60px;height:60px;background:cyan;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:50px;height:50px;background:red;\"></div><div style=\"position:fixed;top:20px;left:20px;width:60px;height:60px;background:cyan;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/fixed-overlaps-content",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;background:gray;\"></div><div style=\"position:fixed;top:50px;left:50px;width:100px;height:100px;background:red;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:200px;height:200px;background:gray;\"></div><div style=\"position:fixed;top:50px;left:50px;width:100px;height:100px;background:red;\"></div></body></html>",
        is_match: true,
    },
    // ── 4. Z-index stacking ──
    InlineReftestDef {
        id: "css-position/z-index-positive-over-negative",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:1;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:2;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:1;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:2;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/z-index-same-level",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:5;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:5;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:5;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:5;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/z-index-three-layers",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:1;\"></div><div style=\"position:absolute;top:20px;left:20px;width:100px;height:100px;background:green;z-index:3;\"></div><div style=\"position:absolute;top:10px;left:10px;width:100px;height:100px;background:blue;z-index:2;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:1;\"></div><div style=\"position:absolute;top:20px;left:20px;width:100px;height:100px;background:green;z-index:3;\"></div><div style=\"position:absolute;top:10px;left:10px;width:100px;height:100px;background:blue;z-index:2;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/z-index-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:1;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:2;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:2;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:1;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/z-index-large-values",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:100;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:200;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:100px;height:100px;\"><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:red;z-index:100;\"></div><div style=\"position:absolute;top:0;left:0;width:100px;height:100px;background:blue;z-index:200;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 5. Position absolute with percentage offsets ──
    InlineReftestDef {
        id: "css-position/absolute-percent-top-left",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:25%;left:25%;width:50px;height:50px;background:fuchsia;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:25%;left:25%;width:50px;height:50px;background:fuchsia;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-percent-bottom-right",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:10%;right:10%;width:60px;height:60px;background:lime;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;bottom:10%;right:10%;width:60px;height:60px;background:lime;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-percent-vs-px-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:50%;left:50%;width:40px;height:40px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:50px;left:50px;width:40px;height:40px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/absolute-percent-all-sides",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:10%;left:10%;bottom:10%;right:10%;background:silver;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:10%;left:10%;bottom:10%;right:10%;background:silver;\"></div></div></body></html>",
        is_match: true,
    },
    // ── 6. Containing block: absolute inside relative, nested absolutes ──
    InlineReftestDef {
        id: "css-position/absolute-in-relative-container",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;margin:20px;width:200px;height:200px;background:yellow;\"><div style=\"position:absolute;top:10px;left:10px;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;margin:20px;width:200px;height:200px;background:yellow;\"><div style=\"position:absolute;top:10px;left:10px;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/nested-absolute",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:20px;left:20px;width:100px;height:100px;background:red;\"><div style=\"position:absolute;top:10px;left:10px;width:40px;height:40px;background:blue;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:20px;left:20px;width:100px;height:100px;background:red;\"><div style=\"position:absolute;top:10px;left:10px;width:40px;height:40px;background:blue;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-in-absolute",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:150px;height:150px;background:orange;\"><div style=\"position:absolute;bottom:0;right:0;width:50px;height:50px;background:blue;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:0;left:0;width:150px;height:150px;background:orange;\"><div style=\"position:absolute;bottom:0;right:0;width:50px;height:50px;background:blue;\"></div></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/containing-block-shift-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:30px;left:30px;width:200px;height:200px;background:gray;\"><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:60px;left:60px;width:200px;height:200px;background:gray;\"><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: false,
    },
    InlineReftestDef {
        id: "css-position/nested-relative-absolute",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:relative;top:10px;left:10px;width:150px;height:150px;background:green;\"><div style=\"position:absolute;top:5px;left:5px;width:40px;height:40px;background:red;\"></div></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:relative;top:10px;left:10px;width:150px;height:150px;background:green;\"><div style=\"position:absolute;top:5px;left:5px;width:40px;height:40px;background:red;\"></div></div></div></body></html>",
        is_match: true,
    },
    // ── 7. Position with margin/padding interactions ──
    InlineReftestDef {
        id: "css-position/absolute-margin-pushes",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:10px;left:10px;width:80px;height:80px;margin:10px;background:green;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:10px;left:10px;width:80px;height:80px;margin:10px;background:green;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/relative-margin-interaction",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:10px;margin:20px;width:100px;height:100px;background:teal;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;top:10px;margin:20px;width:100px;height:100px;background:teal;\"></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-padding-container",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;padding:20px;background:gray;\"><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:red;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;padding:20px;background:gray;\"><div style=\"position:absolute;top:0;left:0;width:50px;height:50px;background:red;\"></div></div></body></html>",
        is_match: true,
    },
    InlineReftestDef {
        id: "css-position/absolute-margin-vs-no-margin-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:20px;left:20px;width:60px;height:60px;background:blue;\"></div></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"position:relative;width:200px;height:200px;\"><div style=\"position:absolute;top:20px;left:20px;margin:15px;width:60px;height:60px;background:blue;\"></div></div></body></html>",
        is_match: false,
    },
    // ── 8. Mismatch cases: different positions produce different visuals ──
    InlineReftestDef {
        id: "css-position/absolute-vs-relative-mismatch",
        category: ReftestCategory::Layout,
        test_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:absolute;top:0;left:100px;width:100px;height:100px;background:blue;\"></div></body></html>",
        ref_html: "<html><body style=\"margin:0\"><div style=\"width:100px;height:100px;background:red;\"></div><div style=\"position:relative;top:0;left:100px;width:100px;height:100px;background:blue;\"></div></body></html>",
        is_match: false,
    },
];

pub fn reftests() -> &'static [InlineReftestDef] {
    REFTESTS
}
