#!/usr/bin/env bash
# Fetch the pinned Web Components testharness subset used by the web-components goal
# (docs/goal/web-components.md, M1 / DC-1): custom-elements/ + shadow-dom/ +
# html/semantics/scripting-1/the-template-element/ window-executable main-thread cases.
#
# 与 fetch-dom-subset.sh 同构（同 WPT_REV pin + raw 拉单文件，显式清单）。
# wpt-data 整体 gitignored，用例按需 fetch、不入库。
#
# 用例级 skip 域（Support Envelope / DC-1 排除项，非静默丢弃——evidence 基线报告同记）：
# - *-ref.html / *-notref.html：reftest 参照页（渲染面，非可执行用例）
# - shadow-dom/ 渲染级 composed tree 用例（slot-fallback-content-00{1..8} /
#   layout-* / directionality-* / restyle-* / shadow-style-* / invalidate-sibling-* /
#   manual-slot-assignment-* / imperative-slot-layout-invalidation-* / user-agent-shadow* /
#   nested-hover-* / accesskey / touch-event-* / wheel-event-* / scroll-* /
#   offsetParent-* / offsetTop-* / focus-within-* / 命中测试四面
#   caretPositionFromPoint / elementFromPoint / highlightsFromPoint / offsetX-offsetY /
#   dragenter-dragleave related-target）：依赖 shadow 树进样式/布局/绘制或几何命中
#   ——等用户点名 Shadow DOM 渲染级专项（goal 排除条款）
# - shadow-dom/focus*/（焦点导航跨 shadow 边界——交互+渲染面）、crashtests/（纯崩溃
#   面，slice 1 不导入）、declarative/（declarative shadow DOM，范围外）、leaktests/
#   （leak harness）、reference-target/（tentative 渲染面）、untriaged/（README）
# - *.window.js（多全局包装形态——runner 无 .window.js wrapper，后续切片评估）、
#   *.xhtml/*.svg（XML/SVG parser 形态，slice 1 排除）
# - custom-elements/reactions/ 全导入（59 用例——per-API CEReactions 断言，
#   template 真实化 + CE 收口的 driving 面）
# - the-template-element 的 css-user-agent-style-sheet-*（reftest/渲染断言，渲染域）
# - the-template-element 的 resources/ iframe fixture 全量拉取（definitions/ 与
#   template-element/ 大量 testInIFrame 变体依赖）

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
WPT_DATA="${REPO_ROOT}/tests/wpt-runner/wpt-data"
WPT_REV="315976933870b34d6ea30e3f6643403edae678ba"
RAW_ROOT="https://raw.githubusercontent.com/web-platform-tests/wpt/${WPT_REV}"

fetch_raw() {
  local relative="$1"
  local target="${WPT_DATA}/${relative}"
  if [[ -s "${target}" && "${FORCE:-0}" != "1" ]]; then
    return 0
  fi
  mkdir -p "$(dirname "${target}")"
  local temporary="${target}.tmp"
  if ! curl --fail --location --silent --show-error \
    --retry 4 --retry-all-errors --retry-delay 2 \
    --connect-timeout 10 --max-time 60 \
    "${RAW_ROOT}/${relative}" -o "${temporary}"; then
    rm -f "${temporary}"
    echo "fetch failed: ${relative}" >&2
    return 1
  fi
  test -e "${temporary}"
  mv "${temporary}" "${target}"
}

SHARED=(
  "resources/testharness.js"
  "resources/testharnessreport.js"
  "common/utils.js"
  "common/get-host-info.sub.js"
  "html/resources/common.js"
)

CE_CASES=(
  "custom-elements/CustomElementRegistry-constructor-and-callbacks-are-held-strongly.html"
  "custom-elements/CustomElementRegistry-getName.html"
  "custom-elements/CustomElementRegistry.html"
  "custom-elements/Document-createElement-customized-builtins.html"
  "custom-elements/Document-createElement.html"
  "custom-elements/Document-createElementNS-customized-builtins.html"
  "custom-elements/Document-createElementNS-prefix-timing.html"
  "custom-elements/Document-createElementNS.html"
  "custom-elements/ElementInternals-accessibility.html"
  "custom-elements/ElementInternals-accessibility.tentative.html"
  "custom-elements/ElementInternals-role.html"
  "custom-elements/HTMLElement-attachInternals.html"
  "custom-elements/HTMLElement-constructor-customized-builtins.html"
  "custom-elements/HTMLElement-constructor.html"
  "custom-elements/adopted-callback.html"
  "custom-elements/append-children-to-new-parent-cycle.html"
  "custom-elements/attribute-changed-callback.html"
  "custom-elements/builtin-coverage.html"
  "custom-elements/connected-callbacks-html-fragment-parsing.html"
  "custom-elements/connected-callbacks-template.html"
  "custom-elements/connected-callbacks.html"
  "custom-elements/cross-realm-callback-report-exception.html"
  "custom-elements/custom-element-reaction-queue.html"
  "custom-elements/customized-built-in-constructor-exceptions.html"
  "custom-elements/disconnected-callbacks.html"
  "custom-elements/element-internals-aria-element-reflection.html"
  "custom-elements/element-internals-behaviors.tentative.html"
  "custom-elements/element-internals-shadowroot.html"
  "custom-elements/enqueue-custom-element-callback-reactions-inside-another-callback.html"
  "custom-elements/historical.html"
  "custom-elements/microtasks-and-constructors.html"
  "custom-elements/overwritten-customElements-global.html"
  "custom-elements/perform-microtask-checkpoint-before-construction.html"
  "custom-elements/prevent-extensions-crash.html"
  "custom-elements/pseudo-class-defined-customized-builtins.html"
  "custom-elements/pseudo-class-defined-print.html"
  "custom-elements/pseudo-class-defined.html"
  "custom-elements/range-and-constructors.html"
  "custom-elements/reaction-timing.html"
  "custom-elements/throw-on-dynamic-markup-insertion-counter-construct.html"
  "custom-elements/throw-on-dynamic-markup-insertion-counter-reactions.html"
  "custom-elements/upgrading.html"
  "custom-elements/when-defined-reentry-crash.html"
  "custom-elements/form-associated/ElementInternals-NotSupportedError.html"
  "custom-elements/form-associated/ElementInternals-behavior-accessibility.tentative.html"
  "custom-elements/form-associated/ElementInternals-form.html"
  "custom-elements/form-associated/ElementInternals-labels.html"
  "custom-elements/form-associated/ElementInternals-reportValidity-bubble.html"
  "custom-elements/form-associated/ElementInternals-reportValidity-delegatesFocus.html"
  "custom-elements/form-associated/ElementInternals-setFormValue-nullish-value.html"
  "custom-elements/form-associated/ElementInternals-setFormValue.html"
  "custom-elements/form-associated/ElementInternals-submit-behavior-dialog.tentative.html"
  "custom-elements/form-associated/ElementInternals-submit-behavior.tentative.html"
  "custom-elements/form-associated/ElementInternals-target-element-is-held-strongly.html"
  "custom-elements/form-associated/ElementInternals-validation.html"
  "custom-elements/form-associated/disabled-delegatesFocus.html"
  "custom-elements/form-associated/fieldset-elements.html"
  "custom-elements/form-associated/focusability.html"
  "custom-elements/form-associated/form-associated-callback.html"
  "custom-elements/form-associated/form-disabled-callback.html"
  "custom-elements/form-associated/form-elements-namedItem.html"
  "custom-elements/form-associated/form-reset-callback.html"
  "custom-elements/form-associated/label-delegatesFocus.html"
  "custom-elements/htmlconstructor/newtarget-customized-builtins.html"
  "custom-elements/htmlconstructor/newtarget.html"
  "custom-elements/parser/parser-constructs-custom-element-in-document-write.html"
  "custom-elements/parser/parser-constructs-custom-element-synchronously.html"
  "custom-elements/parser/parser-constructs-custom-elements-with-is.html"
  "custom-elements/parser/parser-constructs-custom-elements.html"
  "custom-elements/parser/parser-custom-element-in-foreign-content.html"
  "custom-elements/parser/parser-fallsback-to-unknown-element.html"
  "custom-elements/parser/parser-sets-attributes-and-children.html"
  "custom-elements/parser/parser-uses-constructed-element.html"
  "custom-elements/parser/parser-uses-registry-of-owner-document.html"
  "custom-elements/parser/serializing-html-fragments-customized-builtins.html"
  "custom-elements/reactions/customized-builtins/HTMLAreaElement.html"
  "custom-elements/reactions/customized-builtins/HTMLBaseElement.html"
  "custom-elements/reactions/customized-builtins/HTMLButtonElement.html"
  "custom-elements/reactions/customized-builtins/HTMLCanvasElement.html"
  "custom-elements/reactions/customized-builtins/HTMLDataElement.html"
  "custom-elements/reactions/customized-builtins/HTMLDetailsElement.html"
  "custom-elements/reactions/customized-builtins/HTMLEmbedElement.html"
  "custom-elements/reactions/customized-builtins/HTMLFieldSetElement.html"
  "custom-elements/reactions/customized-builtins/HTMLImageElement.html"
  "custom-elements/reactions/customized-builtins/HTMLInputElement.html"
  "custom-elements/reactions/customized-builtins/HTMLLIElement.html"
  "custom-elements/reactions/customized-builtins/HTMLLabelElement.html"
  "custom-elements/reactions/customized-builtins/HTMLMapElement.html"
  "custom-elements/reactions/customized-builtins/HTMLMediaElement.html"
  "custom-elements/reactions/customized-builtins/HTMLMetaElement.html"
  "custom-elements/reactions/customized-builtins/HTMLMeterElement.html"
  "custom-elements/reactions/customized-builtins/HTMLModElement.html"
  "custom-elements/reactions/customized-builtins/HTMLOListElement.html"
  "custom-elements/reactions/customized-builtins/HTMLOptGroupElement.html"
  "custom-elements/reactions/customized-builtins/HTMLParamElement.html"
  "custom-elements/reactions/customized-builtins/HTMLProgressElement.html"
  "custom-elements/reactions/customized-builtins/HTMLQuoteElement.html"
  "custom-elements/reactions/customized-builtins/HTMLSlotElement.html"
  "custom-elements/reactions/customized-builtins/HTMLSourceElement.html"
  "custom-elements/reactions/customized-builtins/HTMLStyleElement.html"
  "custom-elements/reactions/customized-builtins/HTMLTableCellElement.html"
  "custom-elements/reactions/customized-builtins/HTMLTableColElement.html"
  "custom-elements/reactions/customized-builtins/HTMLTimeElement.html"
  "custom-elements/reactions/Animation.html"
  "custom-elements/reactions/AriaMixin-element-attributes.html"
  "custom-elements/reactions/AriaMixin-string-attributes.html"
  "custom-elements/reactions/AriaMixin-string-attributes.tentative.html"
  "custom-elements/reactions/Attr.html"
  "custom-elements/reactions/CSSStyleDeclaration.html"
  "custom-elements/reactions/ChildNode.html"
  "custom-elements/reactions/DOMStringMap.html"
  "custom-elements/reactions/DOMTokenList.html"
  "custom-elements/reactions/Document.html"
  "custom-elements/reactions/Element.html"
  "custom-elements/reactions/ElementContentEditable.html"
  "custom-elements/reactions/HTMLAnchorElement.html"
  "custom-elements/reactions/HTMLElement.html"
  "custom-elements/reactions/HTMLOptionElement.html"
  "custom-elements/reactions/HTMLOptionsCollection.html"
  "custom-elements/reactions/HTMLOutputElement.html"
  "custom-elements/reactions/HTMLSelectElement.html"
  "custom-elements/reactions/HTMLTableElement.html"
  "custom-elements/reactions/HTMLTableRowElement.html"
  "custom-elements/reactions/HTMLTableSectionElement.html"
  "custom-elements/reactions/HTMLTitleElement.html"
  "custom-elements/reactions/NamedNodeMap.html"
  "custom-elements/reactions/Node.html"
  "custom-elements/reactions/ParentNode.html"
  "custom-elements/reactions/Range.html"
  "custom-elements/reactions/Selection.html"
  "custom-elements/reactions/ShadowRoot.html"
  "custom-elements/reactions/with-exceptions.html"
  "custom-elements/registries/Construct.html"
  "custom-elements/registries/CustomElementRegistry-define.html"
  "custom-elements/registries/CustomElementRegistry-initialize.html"
  "custom-elements/registries/CustomElementRegistry-multi-register.html"
  "custom-elements/registries/CustomElementRegistry-upgrade.html"
  "custom-elements/registries/Document-createElement.html"
  "custom-elements/registries/Document-createElementNS.html"
  "custom-elements/registries/Document-customElementRegistry.html"
  "custom-elements/registries/Document-importNode.html"
  "custom-elements/registries/Element-customElementRegistry-exceptions.html"
  "custom-elements/registries/Element-customElementRegistry.html"
  "custom-elements/registries/Element-innerHTML.html"
  "custom-elements/registries/ShadowRoot-init-customElementRegistry.html"
  "custom-elements/registries/ShadowRoot-init-declarative.html"
  "custom-elements/registries/ShadowRoot-innerHTML.html"
  "custom-elements/registries/constructor-reentry-with-different-definition.html"
  "custom-elements/registries/define-customized-builtins.html"
  "custom-elements/registries/define.html"
  "custom-elements/registries/element-mutation-null-registry-removal.html"
  "custom-elements/registries/element-mutation.html"
  "custom-elements/registries/per-document.html"
  "custom-elements/registries/scoped-custom-element-registry-customelementregistry-attribute.html"
  "custom-elements/registries/scoped-registry-append.html"
  "custom-elements/registries/scoped-registry-define-upgrade-criteria.html"
  "custom-elements/registries/scoped-registry-define-upgrade-order.html"
  "custom-elements/registries/scoped-registry-effective-global-registry.html"
  "custom-elements/registries/scoped-registry-initialize-upgrades.html"
  "custom-elements/registries/scoped-registry-initialize.html"
  "custom-elements/registries/scoped-registry-registry-define-get-etc.html"
  "custom-elements/registries/upgrade.html"
  "custom-elements/registries/valid-custom-element-names.html"
  "custom-elements/state/ElementInternals-states.html"
  "custom-elements/state/state-css-selector-nth-of.html"
  "custom-elements/state/state-css-selector-shadow-dom.html"
  "custom-elements/state/state-css-selector.html"
  "custom-elements/state/state-pseudo-class.html"
  "custom-elements/upgrading/Document-importNode-customized-builtins.html"
  "custom-elements/upgrading/Document-importNode.html"
  "custom-elements/upgrading/Node-cloneNode-customized-builtins.html"
  "custom-elements/upgrading/Node-cloneNode.html"
  "custom-elements/upgrading/upgrade-custom-element-error-event.html"
  "custom-elements/upgrading/upgrading-enqueue-reactions.html"
  "custom-elements/upgrading/upgrading-parser-created-element.html"
)

CE_HELPERS=(
  "custom-elements/resources/custom-elements-helpers.js"
  "custom-elements/resources/empty-html-document.html"
  "custom-elements/resources/my-custom-element-html-document.html"
  "custom-elements/resources/navigation-destination.html"
  "custom-elements/reactions/resources/reactions.js"
)

SD_CASES=(
  "shadow-dom/Document-prototype-adoptNode.html"
  "shadow-dom/Document-prototype-currentScript.html"
  "shadow-dom/Document-prototype-importNode.html"
  "shadow-dom/Element-interface-attachShadow-custom-element.html"
  "shadow-dom/Element-interface-attachShadow.html"
  "shadow-dom/Element-interface-shadowRoot-attribute.html"
  "shadow-dom/Extensions-to-Event-Interface.html"
  "shadow-dom/HTMLSlotElement-interface.html"
  "shadow-dom/Node-prototype-cloneNode.html"
  "shadow-dom/Range-prototype-insertNode.html"
  "shadow-dom/ShadowRoot-interface.html"
  "shadow-dom/Slottable-mixin.html"
  "shadow-dom/assign-slottables-after-removing-shadow-tree-from-document.html"
  "shadow-dom/attach-shadow-non-html-namespace.html"
  "shadow-dom/attachShadow-with-ShadowRoot.html"
  "shadow-dom/build-deep-detached-shadow-then-append-text.html"
  "shadow-dom/capturing-and-bubbling-event-listeners-across-shadow-trees.html"
  "shadow-dom/cross-shadow-boundary-selection-remove-splittext-crash.html"
  "shadow-dom/cross-shadow-boundary-selection-splittext-crash.html"
  "shadow-dom/event-composed-path-after-dom-mutation.html"
  "shadow-dom/event-composed-path-with-related-target.html"
  "shadow-dom/event-composed-path.html"
  "shadow-dom/event-composed.html"
  "shadow-dom/event-dispatch-order.tentative.html"
  "shadow-dom/event-inside-shadow-tree.html"
  "shadow-dom/event-inside-slotted-node.html"
  "shadow-dom/event-on-pseudo-element-crash.html"
  "shadow-dom/event-post-dispatch-no-listeners.html"
  "shadow-dom/event-post-dispatch.html"
  "shadow-dom/event-with-related-target.html"
  "shadow-dom/execcommand-insertList-in-shadow.html"
  "shadow-dom/form-control-form-attribute.html"
  "shadow-dom/getElementById-dynamic-001.html"
  "shadow-dom/getElementById-dynamic-002.html"
  "shadow-dom/historical.html"
  "shadow-dom/imperative-slot-api-crash.html"
  "shadow-dom/imperative-slot-api-cross-shadow-root.html"
  "shadow-dom/imperative-slot-api-disconnected.html"
  "shadow-dom/imperative-slot-api-slotchange.html"
  "shadow-dom/imperative-slot-api.html"
  "shadow-dom/imperative-slot-assign-not-slotable-crash.html"
  "shadow-dom/imperative-slot-fallback-clear.html"
  "shadow-dom/imperative-slot-initial-fallback.html"
  "shadow-dom/inserting-fragment-under-shadow-host.html"
  "shadow-dom/invalidate-shadow-dom-crash.html"
  "shadow-dom/nested-slot-remove-crash.html"
  "shadow-dom/shadow-host-child-restyle-crash.html"
  "shadow-dom/shadow-root-clonable.html"
  "shadow-dom/slot-dir-attach-child-crash.html"
  "shadow-dom/slot-dir-attach-child-details-crash.html"
  "shadow-dom/slot-dir-attach-child-meter-crash.html"
  "shadow-dom/slot-dir-attach-child-progress-crash.html"
  "shadow-dom/slot-dir-attach-child-textarea-crash.html"
  "shadow-dom/slot-reconciliation-at-node-removal.html"
  "shadow-dom/slot-with-slottable-slot-in-display-none-subtree-crash.html"
  "shadow-dom/slotchange-customelements.html"
  "shadow-dom/slotchange-event.html"
  "shadow-dom/slotchange.html"
  "shadow-dom/slots-fallback-in-document.html"
  "shadow-dom/slots-fallback.html"
  "shadow-dom/slots-outside-shadow-dom.html"
  "shadow-dom/slots.html"
)

SD_HELPERS=(
  "shadow-dom/resources/Document-prototype-currentScript-helper.js"
  "shadow-dom/resources/event-path-test-helpers.js"
  "shadow-dom/resources/shadow-dom-utils.js"
  "shadow-dom/resources/shadow-dom.js"
)

TPL_CASES=(
  "html/semantics/scripting-1/the-template-element/reflect-html-for.tentative.html"
  "html/semantics/scripting-1/the-template-element/template-construction-in-inactive-document-crash.html"
  "html/semantics/scripting-1/the-template-element/template-table-crash.html"
  "html/semantics/scripting-1/the-template-element/additions-to-parsing-xhtml-documents/node-document.html"
  "html/semantics/scripting-1/the-template-element/additions-to-parsing-xhtml-documents/template-child-nodes.html"
  "html/semantics/scripting-1/the-template-element/additions-to-serializing-xhtml-documents/outerhtml.html"
  "html/semantics/scripting-1/the-template-element/additions-to-the-steps-to-clone-a-node/template-clone-children.html"
  "html/semantics/scripting-1/the-template-element/additions-to-the-steps-to-clone-a-node/templates-copy-document-owner.html"
  "html/semantics/scripting-1/the-template-element/definitions/template-contents-owner-document-type.html"
  "html/semantics/scripting-1/the-template-element/definitions/template-contents-owner-test-001.html"
  "html/semantics/scripting-1/the-template-element/definitions/template-contents-owner-test-002.html"
  "html/semantics/scripting-1/the-template-element/definitions/template-contents.html"
  "html/semantics/scripting-1/the-template-element/innerhtml-on-templates/innerhtml.html"
  "html/semantics/scripting-1/the-template-element/serializing-html-templates/outerhtml.html"
  "html/semantics/scripting-1/the-template-element/template-element/content-attribute.html"
  "html/semantics/scripting-1/the-template-element/template-element/node-document-changes.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-as-a-descendant.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-construction-in-inactive-document-crash.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-content-hierarcy.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-content-in-inactive-document-crash.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-content-move-to-inactive-document-crash.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-content-node-document.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-content.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-descendant-body.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-descendant-frameset.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-descendant-head.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-element-clone-into-inactive-document-crash.html"
  "html/semantics/scripting-1/the-template-element/template-element/template-set-inner-html-in-inactive-document-crash.html"
)

TPL_HELPERS=(
  "html/semantics/scripting-1/the-template-element/resources/end-template-tag-in-body.html"
  "html/semantics/scripting-1/the-template-element/resources/end-template-tag-in-head.html"
  "html/semantics/scripting-1/the-template-element/resources/frameset-end-tag.html"
  "html/semantics/scripting-1/the-template-element/resources/head-template-contents-div-no-end-tag.html"
  "html/semantics/scripting-1/the-template-element/resources/head-template-contents-table-no-end-tag.html"
  "html/semantics/scripting-1/the-template-element/resources/html-start-tag.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-attribute.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-body.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-div-no-end-tag.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-empty.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-frameset.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-head.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-html.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-nested.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-table-no-end-tag.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents-text.html"
  "html/semantics/scripting-1/the-template-element/resources/template-contents.html"
  "html/semantics/scripting-1/the-template-element/resources/template-descendant-body.html"
  "html/semantics/scripting-1/the-template-element/resources/template-descendant-frameset.html"
  "html/semantics/scripting-1/the-template-element/resources/template-descendant-head.html"
  "html/semantics/scripting-1/the-template-element/resources/two-templates.html"
)

for rel in "${SHARED[@]}" "${CE_CASES[@]}" "${CE_HELPERS[@]}" "${SD_CASES[@]}" "${SD_HELPERS[@]}" "${TPL_CASES[@]}" "${TPL_HELPERS[@]}"; do
  fetch_raw "$rel"
done

echo "web-components subset ready: ${#CE_CASES[@]}+${#SD_CASES[@]}+${#TPL_CASES[@]} cases + ${#CE_HELPERS[@]}+${#SD_HELPERS[@]}+${#TPL_HELPERS[@]} helpers @ ${WPT_REV:0:12}"
