org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=7078 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=7078
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7078
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7078
android.useAndroidX=true
