[package]
name = "zero-wasm-sandbox"
description = "非页面 WASM 运行时（Wasmtime/wasmi）"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }

[features]
default = ["wasmi"]
wasmtime = ["dep:wasmtime"]
wasmi = ["dep:wasmi"]

[dependencies.wasmtime]
version = "36"
default-features = false
features = ["runtime", "cranelift", "std"]
optional = true

[dependencies.wasmi]
version = "1.1"
optional = true

[dev-dependencies]
wat = "1"
criterion = { workspace = true }

[[bench]]
name = "wasm_bench"
harness = false
