import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const VERDICT_PATH = join('.acceptance', 'reports', 'verdict.json');
const RESULT_PATH = join('.acceptance', 'reports', 'acceptance-result.json');
const REPORT_PATH = join('.acceptance', 'reports', 'acceptance-chrome-sdk-ui-2026-07-04.md');

if (!existsSync(VERDICT_PATH)) {
  console.error('No verdict file found.');
  process.exit(1);
}

const verdict = JSON.parse(readFileSync(VERDICT_PATH, 'utf-8'));
const result = JSON.parse(readFileSync(RESULT_PATH, 'utf-8'));

const lines = [
  `# ZeroBrowser Chrome SDK UI Acceptance Report`,
  ``,
  `- **Profile:** \`${verdict.profile}\``,
  `- **Environment:** ${verdict.environment}`,
  `- **Date:** ${verdict.date}`,
  `- **Verdict:** **${verdict.verdict}**`,
  ``,
  `## Summary`,
  ``,
  `${verdict.summary}`,
  ``,
  `## Recipe Results`,
  ``,
  `| Recipe | Status |`,
  `|--------|--------|`,
];

for (const r of verdict.details) {
  lines.push(`| ${r.recipe} | ${r.status === 'pass' ? '✅ PASS' : '❌ FAIL'} |`);
}

lines.push(``);
lines.push(`## Artifacts`);
lines.push(``);
lines.push(`Artifact directories in \`.acceptance/artifacts/\`:`);
lines.push(``);

const { execSync } = await import('node:child_process');
const ls = execSync('dir /b /ad ".acceptance\\artifacts"', { encoding: 'utf8' });
for (const dir of ls.trim().split('\n')) {
  const name = dir.trim();
  if (name) {
    lines.push(`- \`${name}/\``);
    const summaryPath = join('.acceptance', 'artifacts', name, 'jsons', '_summary.json');
    if (existsSync(summaryPath)) {
      const s = JSON.parse(readFileSync(summaryPath, 'utf-8'));
      lines.push(`  - Steps: ${s.totalSteps || 'N/A'}, Failures: ${(s.failures || []).length}`);
    }
  }
}

lines.push(``);
lines.push(`---`);
lines.push(`Report generated by acceptance pipeline.`);

writeFileSync(REPORT_PATH, lines.join('\n'));
console.log(`Report written to ${REPORT_PATH}`);
