const translations = {
  en: {
    skip: 'Skip to content', navExperiment: 'Experiment', navProducts: 'Entrypoints', navArchitecture: 'Architecture', navRoadmap: 'Status', navUpdates: 'Updates', navContribute: 'Contribute', github: 'GitHub',
    eyebrow: 'AI-autonomous software engineering experiment', heroTitle: 'Can AI build and maintain<br /><em>a browser?</em>', heroIntro: 'ZeroWeb tests whether AI can keep a large, long-running systems project under development. More than 99.9% of its code is written autonomously by AI. The browser core and product code are in Rust.', explore: 'Read about the experiment <span aria-hidden="true">→</span>', source: 'View source', heroNote: 'Experimental · Not ready for everyday browsing or production use',
    aiShare: 'of project code written autonomously by AI', subjectLabel: 'Test subject', subjectValue: 'A cross-platform browser', constraintLabel: 'Implementation', constraintValue: 'Browser core and product code in Rust', validationLabel: 'Validation', validationValue: 'Builds, tests, WPT and browser comparisons', summaryNote: 'The result is judged by working software and reproducible checks, not generated line count.',
    experimentKicker: 'The experiment', experimentTitle: 'The browser is the test case.', experimentText: 'A browser is large enough to test more than code generation. It requires long-term architecture work, standards implementation, debugging, security boundaries, graphics, and cross-platform integration. Verification runs throughout.', aiRoleTitle: 'What AI does', aiRoleText: 'AI analyzes tasks, changes code, adds tests, runs checks, and investigates failures. The work continues across modules.', controlTitle: 'How the work is constrained', controlText: 'Specifications, module boundaries, review rules, CI, WPT, reftests, and browser comparisons decide whether a change is acceptable.', resultTitle: 'What counts as progress', resultText: 'A larger repository is not the goal. Features must compile, run, and pass the checks appropriate to the behavior being changed.',
    productsKicker: 'Runnable code', productsTitle: 'Two entrypoints into the same project.', browserText: 'The desktop entrypoint used to integrate and test the browser subsystems. It is not yet an everyday browser.', viewBrowser: 'View browser application <span aria-hidden="true">↗</span>', webviewText: 'A Rust API for embedding the page pipeline in host applications. The API and compatibility surface are still evolving.', viewWebview: 'View WebView library <span aria-hidden="true">↗</span>',
    architectureKicker: 'Implementation scope', architectureTitle: 'From request to rendered output.', architectureText: 'The repository separates the systems that load, parse, lay out, and render a page so each part can be implemented and verified independently.', pipeNetwork: 'Network', pipeNetworkSub: 'Resources & navigation', pipeDomSub: 'Document & rules', pipeStyle: 'Style', pipeStyleSub: 'Cascade & computed values', pipeLayout: 'Layout', pipeLayoutSub: 'Geometry & flow', pipeRender: 'Render', pipeRenderSub: 'Paint & composite', readArchitecture: 'Read the architecture guide <span aria-hidden="true">→</span>',
    principlesKicker: 'Engineering method', principlesTitle: 'AI output is checked like engineering work.', principle1Title: 'Browser code in Rust', principle1Text: 'The browser core, host layers, and product code are written in Rust. External crates provide bounded low-level capabilities.', principle2Title: 'Standards-driven', principle2Text: 'Web behavior is verified against WPT, CSSWG reftests, and browser comparisons.', principle3Title: 'Checks are required', principle3Text: 'Formatting, static analysis, unit tests, integration tests, and platform CI guard the repository.', principle4Title: 'Progress has sources', principle4Text: 'Updates link to commits and roadmap items so the experiment can be inspected rather than taken on trust.',
    roadmapKicker: 'Current status', roadmapTitle: 'Useful as an experiment, incomplete as a browser.', roadmapText: 'Core subsystems and runnable entrypoints exist. Real-site compatibility, complete DOM and Web APIs, and everyday browser behavior remain active work.', seeRoadmap: 'See the detailed roadmap <span aria-hidden="true">→</span>', complete: 'Implemented foundations', completeText: 'DOM, CSS, style, layout, rendering, network and security basics', progress: 'In progress', progressText: 'Browser shell, rendering compatibility, DOM and Web API coverage', planned: 'Not yet complete', plannedText: 'WebGL / WebGPU, SVG documents, animation fidelity and real-site behavior',
    quickstartKicker: 'Run the code', quickstartTitle: 'Start with a local build.', quickstartText: 'The repository includes a desktop browser entrypoint and a smaller WebView rendering demo. Platform prerequisites are documented in the README.', browserCommandText: 'Launch the desktop browser entrypoint.', webviewCommandText: 'Run the smallest rendering pipeline demo.', quickstartNote: 'These commands build experimental software; see the README for platform prerequisites and V8 setup.',
    contributeKicker: 'Inspect the experiment', contributeTitle: 'Read the code.<br />Check the evidence.', contributeText: 'The repository, development history, tests, roadmap, and weekly updates are public. Contributions are expected to meet the same verification rules.', visitGithub: 'Visit GitHub <span aria-hidden="true">↗</span>', readContributing: 'Read contributing guide', footer: 'An AI-autonomous software engineering experiment built around a Rust browser.',
    updatesKicker: 'Project journal', updatesTitle: 'Progress, with sources.', updatesText: 'A running record of what changed, what is still in motion, and where each update comes from.', viewAllUpdates: 'View all updates <span aria-hidden="true">→</span>'
  },
  zh: {
    skip: '跳至主要内容', navExperiment: '实验', navProducts: '运行入口', navArchitecture: '架构', navRoadmap: '现状', navUpdates: '最新进展', navContribute: '参与贡献', github: 'GitHub',
    eyebrow: 'AI 自主软件工程实验', heroTitle: 'AI 能否独立开发并长期维护<br /><em>一个浏览器？</em>', heroIntro: 'ZeroWeb 用一个大型、长期的系统工程项目检验 AI 的自主开发能力。项目 99.9% 以上的代码由 AI 自主编写，浏览器核心与产品代码使用 Rust 实现。', explore: '了解这项实验 <span aria-hidden="true">→</span>', source: '查看源码', heroNote: '实验项目 · 尚不适合日常浏览或生产环境',
    aiShare: '项目代码由 AI 自主编写', subjectLabel: '实验对象', subjectValue: '一个跨平台浏览器', constraintLabel: '实现约束', constraintValue: '浏览器核心与产品代码使用 Rust', validationLabel: '验收方式', validationValue: '构建、测试、WPT 与浏览器对比', summaryNote: '实验以可运行的软件和可复现的检查为准，不以生成代码量作为完成标准。',
    experimentKicker: '实验内容', experimentTitle: '浏览器是这项实验的试题。', experimentText: '浏览器足够复杂，检验的不只是代码生成。它需要长期的架构工作、Web 规范实现、故障排查、安全边界、图形渲染、跨平台集成，验证贯穿始终。', aiRoleTitle: 'AI 负责什么', aiRoleText: 'AI 分析任务、修改代码、补充测试、运行检查、排查失败，工作跨模块持续推进。', controlTitle: '如何约束开发过程', controlText: '技术规格、模块边界、评审规则、CI、WPT、reftest 和浏览器对比共同决定一个改动能否被接受。', resultTitle: '什么才算进展', resultText: '仓库变大不是目标。功能需要能够编译和运行，并通过与其行为相对应的检查。',
    productsKicker: '可运行代码', productsTitle: '同一个项目的两个运行入口。', browserText: '用于集成和测试浏览器各子系统的桌面入口，目前还不能作为日常浏览器使用。', viewBrowser: '查看浏览器应用 <span aria-hidden="true">↗</span>', webviewText: '供宿主应用嵌入页面管线的 Rust API，目前 API 和兼容性范围仍在演进。', viewWebview: '查看 WebView 库 <span aria-hidden="true">↗</span>',
    architectureKicker: '实现范围', architectureTitle: '从网络请求到渲染输出。', architectureText: '仓库将页面加载、解析、布局和渲染拆分为职责明确的系统，使每一部分都能独立实现和验证。', pipeNetwork: '网络', pipeNetworkSub: '资源与导航', pipeDomSub: '文档与规则', pipeStyle: '样式', pipeStyleSub: '层叠与计算值', pipeLayout: '布局', pipeLayoutSub: '几何与流动', pipeRender: '渲染', pipeRenderSub: '绘制与合成', readArchitecture: '阅读架构指南 <span aria-hidden="true">→</span>',
    principlesKicker: '工程方法', principlesTitle: 'AI 产出的代码按工程标准验收。', principle1Title: '浏览器代码使用 Rust', principle1Text: '浏览器核心、宿主层和产品代码使用 Rust 编写；外部 crate 只提供边界清楚的底层能力。', principle2Title: '规范驱动', principle2Text: '通过 WPT、CSSWG reftest 和浏览器对比验证 Web 行为。', principle3Title: '检查不可省略', principle3Text: '格式化、静态检查、单元测试、集成测试和多平台 CI 共同守住代码库。', principle4Title: '进展附带来源', principle4Text: '更新记录链接到具体 commit 和路线图，让实验进展可以被检查，而不是只靠项目自述。',
    roadmapKicker: '当前状态', roadmapTitle: '实验已经可运行，浏览器仍不完整。', roadmapText: '核心子系统和运行入口已经存在；真实网站兼容性、完整 DOM 与 Web API，以及日常浏览器行为仍在开发。', seeRoadmap: '查看详细路线图 <span aria-hidden="true">→</span>', complete: '已有基础', completeText: 'DOM、CSS、样式、布局、渲染、网络与安全基础', progress: '进行中', progressText: '浏览器壳、渲染兼容性、DOM 与 Web API 覆盖', planned: '尚未完成', plannedText: 'WebGL / WebGPU、SVG 文档、动画一致性与真实网站行为',
    quickstartKicker: '运行代码', quickstartTitle: '从本地构建开始。', quickstartText: '仓库提供桌面浏览器入口和更小的 WebView 渲染演示，平台前置条件见 README。', browserCommandText: '启动桌面浏览器入口。', webviewCommandText: '运行最小渲染管线演示。', quickstartNote: '这些命令构建的是实验性软件；平台依赖和 V8 设置方法见 README。',
    contributeKicker: '检查这项实验', contributeTitle: '阅读代码。<br />核对证据。', contributeText: '代码仓库、开发历史、测试、路线图和每周进展均公开。贡献代码需要遵守相同的验证规则。', visitGithub: '访问 GitHub <span aria-hidden="true">↗</span>', readContributing: '阅读贡献指南', footer: '一项以 Rust 浏览器为实验对象的 AI 自主软件工程实验。',
    updatesKicker: '项目日志', updatesTitle: '进展，且有来源可查。', updatesText: '持续记录项目发生的变化、正在推进的工作，以及每条更新的事实来源。', viewAllUpdates: '查看全部更新 <span aria-hidden="true">→</span>'
  }
};

function setLanguage(language, persist = true) {
  const selected = translations[language] ? language : 'en';
  document.documentElement.lang = selected === 'zh' ? 'zh-CN' : 'en';
  document.title = selected === 'zh' ? 'ZeroWeb — AI 自主软件工程实验' : 'ZeroWeb — An AI-autonomous software engineering experiment';
  document.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = translations[selected][element.dataset.i18n]; });
  document.querySelectorAll('[data-i18n-html]').forEach((element) => { element.innerHTML = translations[selected][element.dataset.i18nHtml]; });
  document.querySelectorAll('[data-language]').forEach((button) => { button.setAttribute('aria-pressed', String(button.dataset.language === selected)); });
  if (persist) localStorage.setItem('zeroweb-language', selected);
  renderLatestUpdates();
}

const latestUpdates = [];
function renderLatestUpdates() {
  const list = document.getElementById('home-update-list');
  if (!list || !latestUpdates.length) return;
  const lang = document.documentElement.lang.startsWith('zh') ? 'zh' : 'en';
  list.innerHTML = latestUpdates.map((item) => `<article class="update-summary"><span class="update-date">${item.date}</span><h3>${item.title[lang]}</h3><p>${item.summary[lang]}</p></article>`).join('');
}
fetch('updates.json').then((response) => { if (!response.ok) throw new Error('unavailable'); return response.json(); }).then((data) => { latestUpdates.push(...data.slice(0, 3)); renderLatestUpdates(); }).catch(() => {});
const savedLanguage = localStorage.getItem('zeroweb-language');
const detectedLanguage = navigator.language.toLowerCase().startsWith('zh') ? 'zh' : 'en';
setLanguage(savedLanguage || detectedLanguage, false);
document.querySelectorAll('[data-language]').forEach((button) => button.addEventListener('click', () => setLanguage(button.dataset.language)));
